"""
Data models for Pablo.

Models are organized by domain:
- audit.py: Audit logging for HIPAA compliance
- patient.py: Patient management
- scheduling.py: Appointment scheduling API models
- session.py: Therapy sessions, SOAP notes, and API models
  - enums.py: Session-related enumerations
  - soap_note.py: SOAP note dataclasses and Pydantic models
  - transcript.py: Transcript models and parsing helpers
- user.py: Therapist/clinician users
"""

from .audit import AuditAction, AuditLogEntry, ResourceType
from .chat import ChatConversation, ChatMessage
from .chat_api import (
    ChatConversationDetailResponse,
    ChatConversationListResponse,
    ChatConversationResponse,
    ChatMessageResponse,
    CreateChatConversationRequest,
    PreviewChatContextRequest,
    PreviewChatContextResponse,
    SendChatMessageRequest,
    UpdateChatConversationRequest,
)
from .ehr_prompt import EhrPrompt
from .ehr_route import (
    EhrRoute,
    EhrRouteResponse,
    EhrRouteStep,
    EhrRouteStepResponse,
    GoalNavigationRequest,
    GoalNavigationResponse,
    PreviousAction,
    UpdateEhrRouteStepRequest,
)
from .enums import EhrAction, EhrSystem
from .llm_usage import LlmUsageRecord, QuotaStatus, UsageSummary
from .note import Note
from .notes import (
    CreateStandaloneNoteRequest,
    FinalizeNoteRequest,
    NoteResponse,
    PatientNotesListResponse,
    UpdateNoteEditsRequest,
)
from .patient import (
    CloseChartRequest,
    CreatePatientRequest,
    DeletePatientRequest,
    DeletePatientResponse,
    ExportFormat,
    Patient,
    PatientExportData,
    PatientListResponse,
    PatientResponse,
    UpdatePatientRequest,
)
from .patient_document import DocumentCategory, ExtractionStatus, PatientDocument
from .scheduling import (
    AppointmentListResponse,
    AppointmentResponse,
    AvailabilityRuleListResponse,
    AvailabilityRuleResponse,
    CheckConflictsRequest,
    CheckConflictsResponse,
    ConflictResponse,
    CreateAppointmentRequest,
    CreateAvailabilityRuleRequest,
    CreateRecurringAppointmentRequest,
    EditSeriesRequest,
    FreeSlotsResponse,
    TimeSlotResponse,
    UpdateAppointmentRequest,
    UpdateAvailabilityRuleRequest,
)
from .session import (
    CONFIDENCE_THRESHOLDS,
    AssessmentNote,
    FinalizeSessionRequest,
    ObjectiveNote,
    PatientSummary,
    PlanNote,
    ScheduleSessionRequest,
    SessionListResponse,
    SessionResponse,
    SessionSource,
    SessionStatus,
    SessionType,
    SOAPNote,
    SOAPNoteModel,
    SOAPSection,
    SOAPSentence,
    SOAPSentenceModel,
    StructuredSOAPNoteModel,
    SubjectiveNote,
    TherapySession,
    TodaySessionListResponse,
    TodaySessionResponse,
    Transcript,
    TranscriptFormat,
    TranscriptModel,
    TranscriptSegmentModel,
    UpdateSessionMetadataRequest,
    UpdateSessionRatingRequest,
    UpdateSessionStatusRequest,
    UploadSessionRequest,
    UploadTranscriptToSessionRequest,
    VideoPlatform,
)
from .user import (
    AcceptBAARequest,
    AcknowledgeSecurityGuideRequest,
    BAAStatusResponse,
    SecurityGuideStatusResponse,
    UpdateProfessionalInfoRequest,
    UpdateThemeRequest,
    UpdateUserRequest,
    User,
    UserPreferences,
)

__all__ = [
    "CONFIDENCE_THRESHOLDS",
    "AcceptBAARequest",
    "AcknowledgeSecurityGuideRequest",
    "AppointmentListResponse",
    "AppointmentResponse",
    "AssessmentNote",
    "AuditAction",
    "AuditLogEntry",
    "AvailabilityRuleListResponse",
    "AvailabilityRuleResponse",
    "BAAStatusResponse",
    "ChatConversation",
    "ChatConversationDetailResponse",
    "ChatConversationListResponse",
    "ChatConversationResponse",
    "ChatMessage",
    "ChatMessageResponse",
    "CheckConflictsRequest",
    "CheckConflictsResponse",
    "CloseChartRequest",
    "ConflictResponse",
    "CreateAppointmentRequest",
    "CreateAvailabilityRuleRequest",
    "CreateChatConversationRequest",
    "CreatePatientRequest",
    "CreateRecurringAppointmentRequest",
    "CreateStandaloneNoteRequest",
    "DeletePatientRequest",
    "DeletePatientResponse",
    "DocumentCategory",
    "EditSeriesRequest",
    "EhrAction",
    "EhrPrompt",
    "EhrRoute",
    "EhrRouteResponse",
    "EhrRouteStep",
    "EhrRouteStepResponse",
    "EhrSystem",
    "ExportFormat",
    "ExtractionStatus",
    "FinalizeNoteRequest",
    "FinalizeSessionRequest",
    "FreeSlotsResponse",
    "GoalNavigationRequest",
    "GoalNavigationResponse",
    "LlmUsageRecord",
    "Note",
    "NoteResponse",
    "ObjectiveNote",
    "Patient",
    "PatientDocument",
    "PatientExportData",
    "PatientListResponse",
    "PatientNotesListResponse",
    "PatientResponse",
    "PatientSummary",
    "PlanNote",
    "PreviewChatContextRequest",
    "PreviewChatContextResponse",
    "PreviousAction",
    "QuotaStatus",
    "ResourceType",
    "SOAPNote",
    "SOAPNoteModel",
    "SOAPSection",
    "SOAPSentence",
    "SOAPSentenceModel",
    "ScheduleSessionRequest",
    "SecurityGuideStatusResponse",
    "SendChatMessageRequest",
    "SessionListResponse",
    "SessionResponse",
    "SessionSource",
    "SessionStatus",
    "SessionType",
    "StructuredSOAPNoteModel",
    "SubjectiveNote",
    "TherapySession",
    "TimeSlotResponse",
    "TodaySessionListResponse",
    "TodaySessionResponse",
    "Transcript",
    "TranscriptFormat",
    "TranscriptModel",
    "TranscriptSegmentModel",
    "UpdateAppointmentRequest",
    "UpdateAvailabilityRuleRequest",
    "UpdateChatConversationRequest",
    "UpdateEhrRouteStepRequest",
    "UpdateNoteEditsRequest",
    "UpdatePatientRequest",
    "UpdateProfessionalInfoRequest",
    "UpdateSessionMetadataRequest",
    "UpdateSessionRatingRequest",
    "UpdateSessionStatusRequest",
    "UpdateThemeRequest",
    "UpdateUserRequest",
    "UploadSessionRequest",
    "UploadTranscriptToSessionRequest",
    "UsageSummary",
    "User",
    "UserPreferences",
    "VideoPlatform",
]
