steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/pablo/backend-base:latest'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/pablo/backend-base:v${_DATE_TAG}'
      - '-f'
      - 'backend/Dockerfile.base'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/pablo/backend-base:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/pablo/backend-base:v${_DATE_TAG}'

substitutions:
  _DATE_TAG: '00000000'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'
