steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--dockerfile=backend/Dockerfile.base'
      - '--context=.'
      - '--destination=us-central1-docker.pkg.dev/$PROJECT_ID/pablo/backend-base:latest'
      - '--destination=us-central1-docker.pkg.dev/$PROJECT_ID/pablo/backend-base:v${_DATE_TAG}'
      - '--cache=true'
      - '--cache-ttl=720h'

substitutions:
  _DATE_TAG: '00000000'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'
