# Copyright (c) 2026 Pablo Health, LLC. Licensed under AGPL-3.0.

"""Regenerate ``backend/app/db/platform_template.sql`` from the platform chain.

The platform template is the **canonical DDL for the platform schema**. It is
what builds that schema on a fresh install, and the platform chain's baseline
revision is what applies it — so there is one copy of the DDL, not two.

**Why the platform schema needs this at all.** It used to be built by
``PlatformBase.metadata.create_all``, which meant the ORM models were its only
source of truth. ``create_all`` emits tables, columns and indexes and nothing
else, so every other kind of object had to live somewhere else — and measurably
did. At the time this file was written, the fully-migrated platform schema
carried, beyond what ``create_all`` could produce:

  * 3 CHECK constraints,
  * 1 row policy and the RLS switch behind it (``panel_applications``),
  * 1 trigger and the function it calls (the pentest-tenant guards),
  * 2 partial indexes on ``practices`` that no model declared.

A capture keeps all of that without anyone having to remember it. An authored
baseline keeps it only if its author notices each one — and the reverse diff was
empty, so ``create_all`` contributed nothing the migrations did not. See
PABLO-k7it, and ``regen_tenant_template.py`` for the same argument already won
on the tenant side (bug PABLO-API-500, the 2026-05-17 pentest: fresh tenants
stamped at head without ``has_patient_access`` ever being created in them).

Two modes:

``--bootstrap-from-legacy``
    Build the schema the way a deploy built it BEFORE this chain existed — the
    tenant chain's env.py, which runs ``create_all`` and then every tenant-chain
    migration on top — and capture that. Used once, to mint the first template
    from the shape that was actually running. Kept afterwards so the provenance
    of that file is reproducible rather than a matter of trust.

Default (no flag)
    Build the schema from the committed template plus this chain, by running
    ``alembic -n platform upgrade head`` from empty, and capture the result.
    This is what CI runs: regenerate, then ``git diff --exit-code``. It fails
    when a revision landed without the template being regenerated.

Run::

    poetry run python backend/scripts/regen_platform_schema.py

Needs Docker (testcontainers). The companion gate is ``alembic -n platform
check``, which catches the other direction — a model changed with no revision
behind it.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
TEMPLATE_PATH = BACKEND_DIR / "app" / "db" / "platform_template.sql"

#: The chain's own bookkeeping table. Deliberately NOT captured: alembic creates
#: it when it is absent, so a template carrying it would have the template and
#: alembic racing to create the same object, and the round-trip dump would never
#: match the file it came from.
VERSION_TABLE = "alembic_version_platform"

# Prologue ``SET`` statements pg_dump emits — session-level tweaks for dump
# fidelity, not part of the schema, and applying them to a live database is at
# best noise.
_PROLOGUE_PREFIXES = (
    "SET statement_timeout",
    "SET lock_timeout",
    "SET idle_in_transaction_session_timeout",
    "SET client_encoding",
    "SET standard_conforming_strings",
    "SELECT pg_catalog.set_config",
    "SET check_function_bodies",
    "SET xmloption",
    "SET client_min_messages",
    "SET row_security",
    "SET default_tablespace",
    "SET default_table_access_method",
    "SET transaction_timeout",
)

_HEADER = """-- Auto-generated by backend/scripts/regen_platform_schema.py.
-- DO NOT EDIT MANUALLY.
--
-- Canonical DDL for the ``platform`` schema. Applied by the platform chain's
-- baseline revision, which is how a fresh install gets this schema; existing
-- installs are stamped at that revision instead, because they already have it.
--
-- Objects here that no ORM model can express — row policies, triggers and their
-- functions, CHECK constraints, partial indexes — are the reason this is a
-- capture rather than something generated from the models. See
-- backend/scripts/regen_platform_schema.py.
--
-- Regenerate after any revision in backend/alembic_platform/ that touches DDL:
--   poetry run python backend/scripts/regen_platform_schema.py
"""


def _bring_up_postgres() -> tuple[str, object]:
    """Start a disposable Postgres; return (url, container)."""
    # Reaper container fails on Docker Desktop on macOS; pytest config does the
    # same thing. Must be set before testcontainers is imported.
    os.environ.setdefault("TESTCONTAINERS_RYUK_DISABLED", "true")
    from testcontainers.postgres import PostgresContainer

    container = PostgresContainer(
        "postgres:16-alpine",
        username="pablo",
        password="pablo_dev",  # noqa: S106
        dbname="pablo",
        driver=None,
    )
    container.start()
    return container.get_connection_url(), container


def _run_alembic(database_url: str, args: list[str]) -> None:
    """Run alembic in a subprocess against ``database_url``.

    A subprocess rather than an in-process ``command.upgrade`` so a failed
    migration is a clean non-zero exit instead of half-imported alembic state
    inside this interpreter.

    Invoked as ``sys.executable -m alembic`` rather than ``poetry run alembic``,
    which matters in a git worktree: poetry resolves no environment there and
    falls through to whatever ``alembic`` is first on PATH — on a machine with
    anaconda installed, a Python 3.10 that dies on ``sessionmaker[Session]``
    with ``TypeError: 'type' object is not subscriptable``, an error that says
    nothing about the interpreter being wrong. CI runs this script with
    ``poetry run python``, so the running interpreter is already the right one.
    """
    env = os.environ.copy()
    env["DATABASE_URL"] = database_url
    env["DATABASE_BACKEND"] = "postgres"
    result = subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=BACKEND_DIR,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(f"alembic {' '.join(args)} failed (exit {result.returncode})")


def _pg_dump_platform_schema(container: object) -> str:
    """``pg_dump --schema-only --schema=platform`` against the test DB.

    Runs ``pg_dump`` *inside* the container via ``docker exec`` so the client
    version always matches the server — the host's ``pg_dump`` is often older
    than the testcontainers image and refuses to dump (``server version: 16.x;
    pg_dump version: 14.x``).

    ``--no-owner`` / ``--no-privileges`` strip ownership and GRANTs: role names
    differ per deployment, and the one conditional grant this schema needs
    (``pablo_credentialing_ops``) is applied by a migration that checks whether
    the role exists, not baked in here.
    """
    container_id = container.get_wrapped_container().id  # type: ignore[attr-defined]
    cmd = [
        "docker",
        "exec",
        container_id,
        "pg_dump",
        "--schema-only",
        "--schema=platform",
        "--no-owner",
        "--no-privileges",
        "--no-comments",
        "--no-tablespaces",
        "--no-publications",
        "--no-subscriptions",
        "-U",
        "pablo",
        "pablo",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit(f"pg_dump (in container) failed (exit {result.returncode})")
    return result.stdout


def _is_noise(stripped: str) -> bool:
    """Whether a (stripped, non-empty) dump line belongs in the template.

    Four kinds of line do not:

    * pg_dump section banners (``-- Name: ...``), which add diff churn and no
      information.
    * The dump prologue's session ``SET``s — fidelity settings for a restore, not
      schema, and applying them to a live session is at best noise.
    * The schema's own creation: the caller makes it, both in env.py and in the
      baseline revision before it applies this file.
    * ``\\restrict`` / ``\\unrestrict``, psql meta-commands that pg_dump 17+ emits
      to fence its output against older psql. Not valid SQL, so they have to go
      before anything executes this.
    """
    return (
        stripped.startswith("--")
        or stripped.startswith(_PROLOGUE_PREFIXES)
        or stripped.startswith("CREATE SCHEMA platform;")
        or stripped.startswith("CREATE SCHEMA IF NOT EXISTS platform")
        or stripped.startswith("ALTER SCHEMA platform OWNER")
        or stripped.startswith(("\\restrict", "\\unrestrict"))
    )


def _post_process(dump: str) -> str:
    """Turn raw pg_dump output into the committed template."""
    out_lines: list[str] = []
    skipping_version_table = False

    for line in dump.splitlines():
        stripped = line.strip()

        # Drop the chain's own bookkeeping table, statement by statement. The
        # CREATE spans lines, so track it until its terminating ``);``.
        if skipping_version_table:
            if stripped.endswith(");"):
                skipping_version_table = False
            continue
        if re.match(rf"CREATE TABLE platform\.{VERSION_TABLE}\b", stripped):
            skipping_version_table = True
            continue
        if VERSION_TABLE in stripped:
            # Its PK constraint, and anything else naming it.
            continue

        if not stripped:
            out_lines.append(line)
            continue
        if _is_noise(stripped):
            continue

        out_lines.append(line)

    # Collapse runs of blank lines to one. Stripping pg_dump's section banners
    # leaves the gaps they sat in, and how many gaps there are depends on how
    # many banners the dump happened to emit — which changes when objects move
    # between sections. Left alone, that alone can make the CI diff fail on a
    # change that is purely whitespace.
    collapsed: list[str] = []
    for line in out_lines:
        if not line.strip() and collapsed and not collapsed[-1].strip():
            continue
        collapsed.append(line)

    body = "\n".join(collapsed).strip() + "\n"
    return _HEADER + "\n" + body


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--bootstrap-from-legacy",
        action="store_true",
        help=(
            "Capture the pre-chain shape (tenant chain env.py: create_all plus "
            "every tenant-chain migration) instead of the template-plus-chain "
            "shape. For minting the first template only."
        ),
    )
    args = parser.parse_args()

    if shutil.which("pg_dump") is None:
        raise SystemExit(
            "pg_dump not found on PATH. Install Postgres client tools "
            "(brew install postgresql, apt-get install postgresql-client, etc.)."
        )

    container = None
    try:
        url, container = _bring_up_postgres()
        if args.bootstrap_from_legacy:
            # The tenant chain's env.py bootstraps the platform schema itself.
            _run_alembic(url, ["upgrade", "head"])
        else:
            _run_alembic(url, ["-n", "platform", "upgrade", "head"])
        dump = _pg_dump_platform_schema(container)
    finally:
        if container is not None:
            container.stop()  # type: ignore[attr-defined]

    template = _post_process(dump)

    # Write to a temp file in the same directory and rename — atomic on POSIX,
    # so a killed run cannot leave a half-written template behind.
    TEMPLATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        dir=TEMPLATE_PATH.parent,
        delete=False,
        suffix=".sql.tmp",
    ) as tmp:
        tmp.write(template)
        tmp_path = Path(tmp.name)
    tmp_path.replace(TEMPLATE_PATH)

    print(f"Wrote {TEMPLATE_PATH} ({len(template):,} bytes)")


if __name__ == "__main__":
    main()
