# Copyright (c) 2026 Pablo Health, LLC. Licensed under AGPL-3.0.

"""Regenerate ``backend/app/db/tenant_template.sql`` from alembic head.

The tenant template SQL is the **canonical schema for a freshly-provisioned
tenant**. ``create_practice_schema`` applies this file (with the target
schema name substituted) instead of the old
``Base.metadata.create_all + enable_rls_on_schema``
pair — that pair silently dropped raw-SQL DDL (functions, triggers,
custom types) that lived only in alembic migrations, and bug PABLO-API-500
on the 2026-05-17 pentest was the consequence: fresh tenants were stamped
at alembic-head without ``has_patient_access`` ever being created in them.
Column shape evolution (the historical ``_migrate_practice_columns``
boot patch — VARCHAR datetime widening, late ``ADD COLUMN`` calls) now
lives in the alembic chain itself (revision ``b7de65c29385``), so a
regenerated dump faithfully reflects it.

This script:
  1. Brings up a disposable Postgres via testcontainers.
  2. Runs ``alembic upgrade head`` against it — same env.py the platform
     uses, so the result is whatever real prod migrations produce.
  3. ``pg_dump --schema=practice`` to capture every object that lives in
     the canonical tenant schema, including function bodies and indexes.
  4. Post-processes:
       * Strips ``CREATE SCHEMA practice`` (the caller creates the target
         schema).
       * Strips dump-prologue ``SET`` statements (transaction_timeout,
         client_encoding, etc.) — not relevant for applying to a live DB.
       * Strips ``DROP ... IF EXISTS`` statements pg_dump emits with
         ``--clean`` (we don't pass --clean; this is belt-and-suspenders).
       * Strips ownership / privilege noise (--no-owner --no-privileges
         handle most of this but a few ALTER ... OWNER lines slip through
         depending on pg_dump version).
       * Replaces every ``practice.`` qualification with the literal
         placeholder ``__TENANT_SCHEMA__`` — ``create_practice_schema``
         does the substitution at apply time.
       * Keeps the ``alembic_version`` row exactly as dumped, so applying
         the template both creates tables and stamps the schema at HEAD
         in a single SQL transaction. No separate ``_stamp_alembic_at_head``
         call is needed.
  5. Writes the result to ``backend/app/db/tenant_template.sql``.

Run::

    poetry run python backend/scripts/regen_tenant_template.py

CI should regenerate the file and ``git diff --exit-code`` to enforce
"template stays in sync with alembic head".
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

TENANT_SCHEMA_PLACEHOLDER = "__TENANT_SCHEMA__"
TEMPLATE_PATH = Path(__file__).resolve().parents[1] / "app" / "db" / "tenant_template.sql"
BACKEND_DIR = Path(__file__).resolve().parents[1]

# Prologue ``SET`` statements pg_dump emits — these are session-level
# tweaks for dump fidelity, not part of the schema, and applying them
# inside a production session is at best noise and at worst harmful.
_PROLOGUE_PREFIXES = (
    "SET statement_timeout",
    "SET lock_timeout",
    "SET idle_in_transaction_session_timeout",
    "SET client_encoding",
    "SET standard_conforming_strings",
    "SELECT pg_catalog.set_config",
    "SET check_function_bodies",
    "SET xmloption",
    "SET client_min_messages",
    "SET row_security",
    "SET default_tablespace",
    "SET default_table_access_method",
    "SET transaction_timeout",
)

_HEADER = """-- Auto-generated by backend/scripts/regen_tenant_template.py.
-- DO NOT EDIT MANUALLY.
--
-- Canonical schema for a freshly-provisioned tenant. Applied by
-- app.db.provisioning.create_practice_schema after the target schema
-- has been created. The placeholder __TENANT_SCHEMA__ is substituted
-- with the real schema name before execution.
--
-- Regenerate after any alembic revision that touches DDL:
--   poetry run python backend/scripts/regen_tenant_template.py
"""


def _bring_up_postgres() -> tuple[str, object]:
    """Start a disposable Postgres container; return (url, container)."""
    # Reaper container fails on Docker Desktop on macOS; pytest config does
    # the same thing. Must be set before testcontainers is imported.
    os.environ.setdefault("TESTCONTAINERS_RYUK_DISABLED", "true")
    from testcontainers.postgres import PostgresContainer

    container = PostgresContainer(
        "postgres:16-alpine",
        username="pablo",
        password="pablo_dev",  # noqa: S106
        dbname="pablo",
        driver=None,
    )
    container.start()
    return container.get_connection_url(), container


def _run_alembic_upgrade(database_url: str) -> None:
    """Apply ``alembic upgrade head`` against the target DB.

    Runs via ``poetry run`` in a subprocess so we use the same env the
    Makefile / CI runs, and so a failed migration produces a clean
    non-zero exit instead of a half-imported alembic state inside this
    Python process.
    """
    env = os.environ.copy()
    env["DATABASE_URL"] = database_url
    env["DATABASE_BACKEND"] = "postgres"
    result = subprocess.run(
        ["poetry", "run", "alembic", "upgrade", "head"],
        cwd=BACKEND_DIR,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stdout)
        sys.stderr.write(result.stderr)
        raise SystemExit(f"alembic upgrade head failed (exit {result.returncode})")


def _pg_dump_practice_schema(container) -> str:
    """``pg_dump --schema-only --schema=practice`` against the test DB.

    Runs ``pg_dump`` *inside* the postgres container via ``docker exec``
    so the client version always matches the server. The host's
    ``pg_dump`` is often older than the testcontainers postgres image
    and refuses to dump (``server version: 16.x; pg_dump version: 14.x``).

    ``--no-owner`` / ``--no-privileges`` strip ownership and GRANTs since
    fresh tenants run as the same role and don't need cross-role grants
    baked into the template. ``--no-comments`` keeps the file readable.
    """
    container_id = container.get_wrapped_container().id
    cmd = [
        "docker",
        "exec",
        container_id,
        "pg_dump",
        "--schema-only",
        "--schema=practice",
        "--no-owner",
        "--no-privileges",
        "--no-comments",
        "--no-tablespaces",
        "--no-publications",
        "--no-subscriptions",
        "-U",
        "pablo",
        "pablo",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit(f"pg_dump (in container) failed (exit {result.returncode})")
    return result.stdout


def _post_process(dump: str) -> str:
    """Turn raw pg_dump output into an apply-anywhere tenant template."""
    out_lines: list[str] = []
    for raw_line in dump.splitlines():
        line = raw_line
        stripped = line.strip()

        if not stripped:
            out_lines.append(line)
            continue
        if stripped.startswith("--"):
            # Drop pg_dump section banners (-- Name: ..., -- Data for ...);
            # they reference ``practice`` which would be misleading after
            # rewrite. Keep blank lines for readability.
            continue
        if stripped.startswith(_PROLOGUE_PREFIXES):
            continue
        if stripped.startswith("CREATE SCHEMA practice;") or stripped.startswith(
            "CREATE SCHEMA IF NOT EXISTS practice"
        ):
            # The caller creates the target schema with the substituted
            # name — don't recreate ``practice`` itself.
            continue
        if stripped.startswith("ALTER SCHEMA practice OWNER"):
            continue
        if stripped.startswith("\\restrict") or stripped.startswith("\\unrestrict"):
            # psql meta-commands emitted by pg_dump 17+ to fence the
            # dump against execution by older psql. Not valid SQL — must
            # be stripped before feeding to SQLAlchemy.
            continue

        # Replace every "practice." qualifier with the placeholder. Use a
        # regex anchored to a word boundary on the left so we don't match
        # ``my_practice.foo`` if any such identifier ever existed.
        line = re.sub(r"(?<![A-Za-z0-9_])practice\.", f"{TENANT_SCHEMA_PLACEHOLDER}.", line)

        out_lines.append(line)

    body = "\n".join(out_lines).rstrip() + "\n"
    return _HEADER + "\n" + body


def main() -> None:
    if shutil.which("pg_dump") is None:
        raise SystemExit(
            "pg_dump not found on PATH. Install Postgres client tools "
            "(brew install postgresql, apt-get install postgresql-client, etc.)."
        )

    container = None
    try:
        url, container = _bring_up_postgres()
        _run_alembic_upgrade(url)
        dump = _pg_dump_practice_schema(container)
    finally:
        if container is not None:
            container.stop()

    template = _post_process(dump)

    # Write to a temp file in the same directory and rename — atomic on
    # POSIX. Avoids leaving a half-written tenant_template.sql if the
    # script is killed.
    TEMPLATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        dir=TEMPLATE_PATH.parent,
        delete=False,
        suffix=".sql.tmp",
    ) as tmp:
        tmp.write(template)
        tmp_path = Path(tmp.name)
    tmp_path.replace(TEMPLATE_PATH)

    print(f"Wrote {TEMPLATE_PATH} ({len(template):,} bytes)")


if __name__ == "__main__":
    main()
