# Copyright (c) 2026 Pablo Health, LLC. Licensed under AGPL-3.0.

"""Render the intake question set as the field-by-field correspondence table.

The intake is ordered and named to match the provider data portal's profile so
the collected record exports into it rather than needing translation. That
claim is only checkable if the correspondence is written down, so it is —
generated from :mod:`app.credentialing.intake` rather than maintained beside
it, because a hand-kept copy is a copy that drifts.

``docs/reference/caqh-intake-field-map.md`` is the committed output, and
``tests/test_intake_question_set.py`` fails if it stops matching.
"""

from __future__ import annotations

from pathlib import Path

from app.credentialing.intake import (
    INTAKE_FIELDS,
    Applicability,
    CaqhSection,
    IntakeField,
    Tier,
)

#: The committed output. Located from this module rather than from a caller's
#: cwd, so the script and the test that checks it agree.
FIELD_MAP_PATH: Path = (
    Path(__file__).resolve().parents[3] / "docs" / "reference" / "caqh-intake-field-map.md"
)

_SECTION_TITLES: dict[CaqhSection, str] = {
    CaqhSection.PERSONAL_INFORMATION: "Personal Information",
    CaqhSection.PROFESSIONAL_IDS: "Professional IDs",
    CaqhSection.EDUCATION_AND_TRAINING: "Education and Professional Training",
    CaqhSection.SPECIALTIES: "Specialties",
    CaqhSection.PRACTICE_LOCATIONS: "Practice Locations",
    CaqhSection.HOSPITAL_AFFILIATIONS: "Hospital Affiliations",
    CaqhSection.CREDENTIAL_CONTACTS: "Credential Contacts",
    CaqhSection.PROFESSIONAL_LIABILITY_INSURANCE: "Professional Liability Insurance",
    CaqhSection.EMPLOYMENT_INFORMATION: "Employment Information",
    CaqhSection.PROFESSIONAL_REFERENCES: "Professional References",
    CaqhSection.DISCLOSURE: "Disclosure",
}

_TIER_LABELS: dict[Tier, str] = {
    Tier.CONFIRM: "0 · confirm",
    Tier.CLAIMS_READY: "1 · claims-ready",
    Tier.CREDENTIALING: "2 · credentialing",
}

_APPLICABILITY_LABELS: dict[Applicability, str] = {
    Applicability.ALL: "everyone",
    Applicability.INDEPENDENT_ONLY: "independently licensed",
    Applicability.SUPERVISED_ONLY: "supervised",
    Applicability.PRESCRIBER_ONLY: "prescribers",
}

_HEADER = """<!-- Generated by backend/app/credentialing/field_map.py. Do not edit by hand. -->

# Intake field map — every question, and where its answer lands

Generated from `backend/app/credentialing/intake.py`. Regenerate with:

```
poetry run python backend/scripts/regen_intake_field_map.py
```

The intake follows the provider data portal's eleven profile sections, in the
order the provider user guide gives them (p31) — see
[caqh-provider-data-portal-rules.md](caqh-provider-data-portal-rules.md). This
table is the evidence for that claim: one row per question, grouped by the
section it exports into, naming the tier that asks it and the column its answer
lands in.

A **target** of `table.column` is a scalar; a bare `table` is a repeating group
with one row per entry. Tier 0 asks nothing — it presents a value and records
the confirmation in `credential_confirmations` regardless of what the target
column says. The few Tier-0 rows targeting `credential_confirmations` itself are
the ones with no home column anywhere else.
"""


def _row(f: IntakeField) -> str:
    applies = _APPLICABILITY_LABELS[f.applies_to]
    required = "required" if f.required else "optional"
    source = f"`{f.source}`" if f.source else "—"
    writer = f"`{f.audited_writer}`" if f.audited_writer else "—"
    return (
        f"| `{f.key}` | {_TIER_LABELS[f.tier]} | {f.kind.value} | `{f.target}` "
        f"| {required} | {applies} | {source} | {writer} |"
    )


def render() -> str:
    """The whole map, in the portal's section order."""
    lines = [_HEADER]
    for section in CaqhSection:
        fields = [f for f in INTAKE_FIELDS if f.section is section]
        lines.append(f"\n## {_SECTION_TITLES[section]}\n")
        if not fields:
            lines.append("_No intake field exports into this section._\n")
            continue
        lines.append(
            "| Key | Tier | Kind | Target | Required | Applies to | Pre-filled from | Written via |"
        )
        lines.append("| --- | --- | --- | --- | --- | --- | --- | --- |")
        lines.extend(_row(f) for f in fields)
        lines.append("")
    return "\n".join(lines)
