# Copyright (c) 2026 Pablo Health, LLC. Licensed under AGPL-3.0.

"""Treatment Plan: the signed, reviewable plan of care.

Generated by cross-note synthesis rather than from one transcript:
problem list, goals and strengths are drafted from the client's intake
and recent session notes. Objectives, interventions, frequency,
discharge criteria and signatures are clinician-authored (no
``ai_hint``), so generation never fills them.
"""

from __future__ import annotations

from .registry import NoteFieldDef, NoteSectionDef, NoteTypeDefinition

TREATMENT_PLAN_DEFINITION = NoteTypeDefinition(
    key="treatment_plan",
    label="Treatment Plan",
    description=(
        "Written treatment plan, signed by clinician — required by CMS "
        "(42 CFR 410.43), state Medicaid plans, CARF 1.J., Joint Commission "
        "PC.01.03.01, and all major MCOs for continued authorization. Not "
        "separately billable, but a missing or stale plan voids reimbursement "
        "for the underlying therapy sessions. Drafted by cross-note synthesis "
        "from the patient's intake and recent session notes — not from a live "
        "transcript — then reviewed and signed between sessions. Goals must be "
        "measurable; objectives must be SMART and link back to a goal; "
        "interventions must link back to an objective; review_due_date is the "
        "single most common audit failure."
    ),
    tier="core",
    context="patient",
    sections=(
        NoteSectionDef(
            key="identification",
            label="Identification",
            fields=(
                NoteFieldDef(
                    key="plan_date",
                    label="Plan Date",
                    kind="text",
                ),
                NoteFieldDef(
                    key="plan_type",
                    label="Plan Type",
                    kind="text",
                ),
                NoteFieldDef(
                    key="review_due_date",
                    label="Review Due Date",
                    kind="text",
                ),
            ),
        ),
        NoteSectionDef(
            key="clinical",
            label="Clinical",
            fields=(
                NoteFieldDef(
                    key="dsm5_diagnosis",
                    label="DSM-5 Diagnosis",
                    kind="list",
                ),
                NoteFieldDef(
                    key="problem_list",
                    label="Problem List",
                    kind="list",
                    ai_hint=(
                        "Draft the patient's clinical problems from the intake note's "
                        "presenting concern, history of present illness, and DSM-5 "
                        "impressions. One concise problem per item, in clinical language "
                        "the clinician will refine. Do not invent problems not supported "
                        "by the source notes."
                    ),
                ),
                NoteFieldDef(
                    key="strengths_supports",
                    label="Strengths & Supports",
                    kind="list",
                    ai_hint=(
                        "Draft from the intake's strengths section and any supports the "
                        "patient described (relationships, employment, recovery capital). "
                        "One item per strength or support; mirror the patient's framing "
                        "where it is in the source notes."
                    ),
                ),
            ),
        ),
        NoteSectionDef(
            key="goals",
            label="Goals",
            fields=(
                NoteFieldDef(
                    key="goals",
                    label="Long-Term Goals",
                    kind="list",
                    ai_hint=(
                        "Draft long-term goals from intake themes plus recent session "
                        "progress. One goal per item; prefer the patient's own words "
                        "where they appear in the source notes. Goals are aspirational "
                        "outcomes — the clinician will decompose them into SMART "
                        "objectives separately, so do not pre-write objectives here."
                    ),
                ),
            ),
        ),
        NoteSectionDef(
            key="objectives",
            label="Objectives",
            fields=(
                NoteFieldDef(
                    key="objectives",
                    label="SMART Objectives",
                    kind="list",
                ),
            ),
        ),
        NoteSectionDef(
            key="interventions",
            label="Interventions",
            fields=(
                NoteFieldDef(
                    key="interventions",
                    label="Interventions",
                    kind="list",
                ),
            ),
        ),
        NoteSectionDef(
            key="coordination",
            label="Coordination",
            fields=(
                NoteFieldDef(
                    key="care_coordination",
                    label="Care Coordination",
                    kind="list",
                ),
            ),
        ),
        NoteSectionDef(
            key="discharge",
            label="Discharge",
            fields=(
                NoteFieldDef(
                    key="discharge_termination_criteria",
                    label="Discharge / Termination Criteria",
                    kind="text",
                ),
            ),
        ),
        NoteSectionDef(
            key="participation",
            label="Participation",
            fields=(
                NoteFieldDef(
                    key="patient_participated_in_plan",
                    label="Patient Participated in Plan",
                    kind="text",
                ),
                NoteFieldDef(
                    key="patient_signature_present",
                    label="Patient Signature Present",
                    kind="text",
                ),
            ),
        ),
        NoteSectionDef(
            key="signature",
            label="Signature",
            fields=(
                NoteFieldDef(
                    key="clinician_signature",
                    label="Clinician Signature",
                    kind="text",
                ),
                NoteFieldDef(
                    key="signed_at",
                    label="Signed At",
                    kind="text",
                ),
                NoteFieldDef(
                    key="supervisor_signature",
                    label="Supervisor Signature",
                    kind="text",
                ),
                NoteFieldDef(
                    key="supervisor_signed_at",
                    label="Supervisor Signed At",
                    kind="text",
                ),
                NoteFieldDef(
                    key="review_history",
                    label="Review History",
                    kind="list",
                ),
            ),
        ),
    ),
)
