-- Auto-generated by backend/scripts/regen_platform_schema.py.
-- DO NOT EDIT MANUALLY.
--
-- Canonical DDL for the ``platform`` schema. Applied by the platform chain's
-- baseline revision, which is how a fresh install gets this schema; existing
-- installs are stamped at that revision instead, because they already have it.
--
-- Objects here that no ORM model can express — row policies, triggers and their
-- functions, CHECK constraints, partial indexes — are the reason this is a
-- capture rather than something generated from the models. See
-- backend/scripts/regen_platform_schema.py.
--
-- Regenerate after any revision in backend/alembic_platform/ that touches DDL:
--   poetry run python backend/scripts/regen_platform_schema.py

CREATE FUNCTION platform.practices_pentest_immutable() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF OLD.is_pentest IS DISTINCT FROM NEW.is_pentest THEN
                RAISE EXCEPTION
                    'is_pentest is immutable; drop and recreate the tenant'
                    USING ERRCODE = 'check_violation';
            END IF;
            RETURN NEW;
        END;
        $$;

CREATE TABLE platform.allowed_emails (
    email character varying(255) NOT NULL,
    practice_id character varying(128),
    added_by character varying(255) NOT NULL,
    added_at timestamp with time zone NOT NULL
);

CREATE TABLE platform.booking_links (
    id uuid NOT NULL,
    slug character varying(64) NOT NULL,
    user_id uuid NOT NULL,
    practice_id character varying(128),
    host_name character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    appointment_type_id uuid NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    require_email_confirmation boolean DEFAULT true NOT NULL,
    deleted_at timestamp with time zone
);

CREATE TABLE platform.claim_routes (
    control_number character varying(17) NOT NULL,
    practice_id character varying(128) NOT NULL,
    user_id character varying(128) NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE platform.companion_devices (
    install_id character varying(64) NOT NULL,
    user_id uuid NOT NULL,
    device_public_key_jwk jsonb NOT NULL,
    jkt character varying(64) NOT NULL,
    key_storage character varying(16) NOT NULL,
    platform character varying(16) NOT NULL,
    os_version character varying(64),
    hostname_hash character varying(64),
    enrolled_at timestamp with time zone NOT NULL,
    last_seen timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone
);

CREATE TABLE platform.credential_bank_accounts (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    practice_id character varying(128) NOT NULL,
    account_holder_name character varying(255) NOT NULL,
    routing_number_encrypted text NOT NULL,
    routing_number_last4 character varying(4),
    account_number_encrypted text NOT NULL,
    account_number_last4 character varying(4),
    account_type character varying(8) NOT NULL,
    document_id uuid,
    verified_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_credential_bank_accounts_account_type CHECK (((account_type)::text = ANY ((ARRAY['checking'::character varying, 'savings'::character varying])::text[])))
);

ALTER TABLE ONLY platform.credential_bank_accounts FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.credential_confirmations (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    field_key character varying(64) NOT NULL,
    source character varying(32) NOT NULL,
    presented_value text,
    confirmed boolean NOT NULL,
    correction text,
    confirmed_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_credential_confirmations_corrected CHECK ((confirmed OR (correction IS NOT NULL))),
    CONSTRAINT ck_credential_confirmations_source CHECK (((source)::text = ANY ((ARRAY['nppes'::character varying, 'pecos_public_file'::character varying, 'leie_sam'::character varying, 'clinician_profiles'::character varying, 'practice_billing_profile'::character varying])::text[])))
);

ALTER TABLE ONLY platform.credential_confirmations FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.credential_disclosures (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    question_key character varying(64) NOT NULL,
    question_version smallint NOT NULL,
    answer boolean NOT NULL,
    explanation text,
    answered_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_credential_disclosures_explained CHECK (((answer IS NOT TRUE) OR (explanation IS NOT NULL)))
);

ALTER TABLE ONLY platform.credential_disclosures FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.credential_education (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    institution character varying(255) NOT NULL,
    degree character varying(100),
    field_of_study character varying(255),
    start_date date,
    end_date date,
    country character varying(2),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY platform.credential_education FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.credential_employment (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    employer_name character varying(255) NOT NULL,
    "position" character varying(255),
    address_line1 character varying(255),
    address_line2 character varying(255),
    city character varying(100),
    state character varying(2),
    postal_code character varying(20),
    start_date date NOT NULL,
    end_date date,
    preceding_gap_explanation text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY platform.credential_employment FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.credential_government_ids (
    user_id uuid NOT NULL,
    ssn_encrypted text,
    ssn_last4 character varying(4),
    dob_encrypted text,
    tax_id_type character varying(3),
    tax_id_encrypted text,
    tax_id_last4 character varying(4),
    type2_npi character varying(20),
    business_structure character varying(40),
    sole_proprietor boolean,
    supervision_status character varying(16),
    caqh_id character varying(32),
    medicare_intent boolean,
    medicaid_intent boolean,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_credential_government_ids_supervision_status CHECK (((supervision_status IS NULL) OR ((supervision_status)::text = ANY ((ARRAY['independent'::character varying, 'supervised'::character varying])::text[])))),
    CONSTRAINT ck_credential_government_ids_tax_id_type CHECK (((tax_id_type IS NULL) OR ((tax_id_type)::text = ANY ((ARRAY['ein'::character varying, 'ssn'::character varying])::text[]))))
);

ALTER TABLE ONLY platform.credential_government_ids FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.credential_liability_policies (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    practice_id character varying(128) NOT NULL,
    carrier_name character varying(255) NOT NULL,
    policy_number character varying(100),
    per_occurrence_cents bigint,
    aggregate_cents bigint,
    effective_date date,
    expiration_date date,
    is_current boolean NOT NULL,
    document_id uuid,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY platform.credential_liability_policies FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.credential_licenses (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    practice_id character varying(128) NOT NULL,
    license_type character varying(50) NOT NULL,
    license_number character varying(100) NOT NULL,
    state character varying(2) NOT NULL,
    issue_date date,
    expiration_date date,
    status character varying(16) NOT NULL,
    is_primary boolean NOT NULL,
    verification_source character varying(8) NOT NULL,
    verified_at timestamp with time zone,
    document_id uuid,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_credential_licenses_status CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'inactive'::character varying, 'expired'::character varying, 'suspended'::character varying, 'revoked'::character varying])::text[]))),
    CONSTRAINT ck_credential_licenses_verification_source CHECK (((verification_source)::text = ANY ((ARRAY['self'::character varying, 'nppes'::character varying, 'board'::character varying])::text[])))
);

ALTER TABLE ONLY platform.credential_licenses FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.credential_references (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    full_name character varying(255) NOT NULL,
    title character varying(100),
    credential character varying(100),
    organization character varying(255),
    email character varying(255),
    phone character varying(32),
    relationship character varying(100),
    years_known smallint,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY platform.credential_references FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.credential_service_locations (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name character varying(255),
    address_line1 character varying(255) NOT NULL,
    address_line2 character varying(255),
    city character varying(100) NOT NULL,
    state character varying(2) NOT NULL,
    postal_code character varying(20) NOT NULL,
    phone character varying(32),
    fax character varying(32),
    is_primary boolean NOT NULL,
    accepts_new_patients boolean NOT NULL,
    hours jsonb,
    ada_accessible boolean,
    languages jsonb,
    telehealth_only boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY platform.credential_service_locations FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.credential_training (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    program_type character varying(50) NOT NULL,
    institution character varying(255) NOT NULL,
    specialty character varying(255),
    start_date date,
    end_date date,
    supervisor_name character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY platform.credential_training FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.diagnostic_definitions (
    id uuid NOT NULL,
    code character varying(40) NOT NULL,
    version integer NOT NULL,
    display_name character varying(120) NOT NULL,
    evaluator_type character varying(40) NOT NULL,
    params jsonb NOT NULL,
    suggested_icd10 character varying(10),
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE platform.email_tenant_mappings (
    email character varying(255) NOT NULL,
    tenant_id character varying(128) NOT NULL,
    practice_id character varying(128) NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE platform.icd10_codes (
    code character varying(10) NOT NULL,
    description character varying(255) NOT NULL,
    billable boolean NOT NULL,
    category character varying(80)
);

CREATE TABLE platform.launch_intents (
    intent_hash character varying(64) NOT NULL,
    user_id uuid NOT NULL,
    appointment_id character varying(128) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone
);

CREATE TABLE platform.panel_applications (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    practice_id character varying(128) NOT NULL,
    payer_id uuid NOT NULL,
    status character varying(24) NOT NULL,
    action_owner character varying(16) NOT NULL,
    due_at timestamp with time zone,
    awaiting text,
    reference character varying(80),
    submitted_at timestamp with time zone,
    effective_at timestamp with time zone,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_panel_applications_action_owner CHECK (((action_owner)::text = ANY (ARRAY[('pablo'::character varying)::text, ('therapist'::character varying)::text]))),
    CONSTRAINT ck_panel_applications_status CHECK (((status)::text = ANY (ARRAY[('researching'::character varying)::text, ('caqh_ready'::character varying)::text, ('submitted'::character varying)::text, ('in_review'::character varying)::text, ('info_requested'::character varying)::text, ('contract_received'::character varying)::text, ('effective'::character varying)::text, ('closed_panel_appeal'::character varying)::text, ('denied'::character varying)::text, ('recredentialing'::character varying)::text])))
);

ALTER TABLE ONLY platform.panel_applications FORCE ROW LEVEL SECURITY;

CREATE TABLE platform.passkey_backup_codes (
    code_hash character varying(64) NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone
);

CREATE TABLE platform.passkey_challenges (
    challenge_hash character varying(64) NOT NULL,
    ceremony character varying(16) NOT NULL,
    user_id uuid,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone
);

CREATE TABLE platform.passkey_credentials (
    credential_id character varying(255) NOT NULL,
    user_id uuid NOT NULL,
    public_key bytea NOT NULL,
    sign_count bigint DEFAULT '0'::bigint NOT NULL,
    transports jsonb,
    aaguid character varying(36),
    fmt character varying(32),
    attestation_verified boolean DEFAULT false NOT NULL,
    backup_eligible boolean DEFAULT false NOT NULL,
    backup_state boolean DEFAULT false NOT NULL,
    device_label character varying(120),
    created_at timestamp with time zone NOT NULL,
    last_used_at timestamp with time zone,
    revoked_at timestamp with time zone
);

CREATE TABLE platform.platform_audit_logs (
    id uuid NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    actor_user_id character varying(128) NOT NULL,
    action character varying(50) NOT NULL,
    resource_type character varying(30) NOT NULL,
    resource_id character varying(128) NOT NULL,
    tenant_schema character varying(128),
    ip_address character varying(45),
    user_agent text,
    details jsonb
);

CREATE TABLE platform.practices (
    id character varying(128) NOT NULL,
    name character varying(255) NOT NULL,
    schema_name character varying(128) NOT NULL,
    tenant_id character varying(128),
    owner_email character varying(255) NOT NULL,
    owner_user_id uuid,
    product character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_pentest boolean DEFAULT false NOT NULL,
    audio_retention_days integer DEFAULT 365 NOT NULL,
    offboard_scheduled_at timestamp with time zone,
    deleted_at timestamp with time zone,
    provisioning_status character varying(20) DEFAULT 'ready'::character varying NOT NULL,
    address character varying(500),
    phone character varying(50),
    baa_accepted_at timestamp with time zone,
    baa_version character varying(10),
    baa_legal_name character varying(255),
    baa_license_number character varying(100),
    baa_license_state character varying(2),
    baa_practice_name character varying(255),
    baa_business_address character varying(500),
    baa_full_text text,
    edition character varying(20) DEFAULT 'therapist'::character varying NOT NULL,
    CONSTRAINT ck_practices_audio_retention_days_range CHECK (((audio_retention_days >= 30) AND (audio_retention_days <= 2555))),
    CONSTRAINT ck_practices_edition CHECK (((edition)::text = ANY (ARRAY[('therapist'::character varying)::text, ('personal'::character varying)::text]))),
    CONSTRAINT practices_pentest_schema_name CHECK (((is_pentest = false) OR ((schema_name)::text ~~ like_escape('practice\_pentest\_%'::text, '\'::text)))),
    CONSTRAINT practices_provisioning_status_chk CHECK (((provisioning_status)::text = ANY (ARRAY[('in_progress'::character varying)::text, ('ready'::character varying)::text, ('failed'::character varying)::text])))
);

CREATE TABLE platform.processed_payment_events (
    event_id character varying(255) NOT NULL,
    event_type character varying(64) NOT NULL,
    practice_id character varying(128),
    event_created_at timestamp with time zone,
    processed_at timestamp with time zone NOT NULL
);

CREATE TABLE platform.setup_tokens (
    token character varying(64) NOT NULL,
    email character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE platform.system_config (
    key character varying(100) NOT NULL,
    value text NOT NULL,
    description text NOT NULL,
    updated_at timestamp with time zone
);

CREATE TABLE platform.user_identities (
    provider character varying(32) NOT NULL,
    subject_id character varying(64) NOT NULL,
    user_id uuid NOT NULL,
    linked_at timestamp with time zone NOT NULL
);

CREATE TABLE platform.user_preferences (
    user_id uuid NOT NULL,
    preferences jsonb NOT NULL
);

CREATE TABLE platform.users (
    id uuid NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    picture text,
    phone character varying(50),
    status character varying(20) NOT NULL,
    mfa_enrolled_at timestamp with time zone,
    is_platform_admin boolean NOT NULL,
    baa_accepted_at timestamp with time zone,
    baa_version character varying(10),
    legal_name character varying(255),
    provider_type character varying(32),
    security_guide_acknowledged_at timestamp with time zone,
    security_guide_version character varying(20),
    onboarding_state character varying(20),
    profile_basics_completed_at timestamp with time zone,
    chat_quality_review_opt_in boolean NOT NULL,
    chat_quality_review_opt_in_at timestamp with time zone,
    chat_quality_review_opt_out_at timestamp with time zone,
    session_notes_quality_review_opt_in boolean NOT NULL,
    session_notes_quality_review_opt_in_at timestamp with time zone,
    session_notes_quality_review_opt_out_at timestamp with time zone,
    quality_review_consent_prompted_at timestamp with time zone,
    inbox_quality_review_opt_in boolean DEFAULT false NOT NULL,
    inbox_quality_review_opt_in_at timestamp with time zone,
    inbox_quality_review_opt_out_at timestamp with time zone
);

ALTER TABLE ONLY platform.allowed_emails
    ADD CONSTRAINT allowed_emails_pkey PRIMARY KEY (email);

ALTER TABLE ONLY platform.booking_links
    ADD CONSTRAINT booking_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.booking_links
    ADD CONSTRAINT booking_links_slug_key UNIQUE (slug);

ALTER TABLE ONLY platform.claim_routes
    ADD CONSTRAINT claim_routes_pkey PRIMARY KEY (control_number);

ALTER TABLE ONLY platform.companion_devices
    ADD CONSTRAINT companion_devices_pkey PRIMARY KEY (install_id);

ALTER TABLE ONLY platform.credential_bank_accounts
    ADD CONSTRAINT credential_bank_accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.credential_confirmations
    ADD CONSTRAINT credential_confirmations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.credential_disclosures
    ADD CONSTRAINT credential_disclosures_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.credential_education
    ADD CONSTRAINT credential_education_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.credential_employment
    ADD CONSTRAINT credential_employment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.credential_government_ids
    ADD CONSTRAINT credential_government_ids_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY platform.credential_liability_policies
    ADD CONSTRAINT credential_liability_policies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.credential_licenses
    ADD CONSTRAINT credential_licenses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.credential_references
    ADD CONSTRAINT credential_references_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.credential_service_locations
    ADD CONSTRAINT credential_service_locations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.credential_training
    ADD CONSTRAINT credential_training_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.diagnostic_definitions
    ADD CONSTRAINT diagnostic_definitions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.email_tenant_mappings
    ADD CONSTRAINT email_tenant_mappings_pkey PRIMARY KEY (email);

ALTER TABLE ONLY platform.icd10_codes
    ADD CONSTRAINT icd10_codes_pkey PRIMARY KEY (code);

ALTER TABLE ONLY platform.launch_intents
    ADD CONSTRAINT launch_intents_pkey PRIMARY KEY (intent_hash);

ALTER TABLE ONLY platform.panel_applications
    ADD CONSTRAINT panel_applications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.passkey_backup_codes
    ADD CONSTRAINT passkey_backup_codes_pkey PRIMARY KEY (code_hash);

ALTER TABLE ONLY platform.passkey_challenges
    ADD CONSTRAINT passkey_challenges_pkey PRIMARY KEY (challenge_hash);

ALTER TABLE ONLY platform.passkey_credentials
    ADD CONSTRAINT passkey_credentials_pkey PRIMARY KEY (credential_id);

ALTER TABLE ONLY platform.platform_audit_logs
    ADD CONSTRAINT platform_audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.practices
    ADD CONSTRAINT practices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.practices
    ADD CONSTRAINT practices_schema_name_key UNIQUE (schema_name);

ALTER TABLE ONLY platform.practices
    ADD CONSTRAINT practices_tenant_id_key UNIQUE (tenant_id);

ALTER TABLE ONLY platform.processed_payment_events
    ADD CONSTRAINT processed_payment_events_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY platform.setup_tokens
    ADD CONSTRAINT setup_tokens_pkey PRIMARY KEY (token);

ALTER TABLE ONLY platform.system_config
    ADD CONSTRAINT system_config_pkey PRIMARY KEY (key);

ALTER TABLE ONLY platform.diagnostic_definitions
    ADD CONSTRAINT uq_diagnostic_definitions_code_version UNIQUE (code, version);

ALTER TABLE ONLY platform.user_identities
    ADD CONSTRAINT user_identities_pkey PRIMARY KEY (provider, subject_id);

ALTER TABLE ONLY platform.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY platform.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY platform.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY platform.credential_confirmations
    ADD CONSTRAINT ux_credential_confirmations_user_field UNIQUE (user_id, field_key);

ALTER TABLE ONLY platform.credential_disclosures
    ADD CONSTRAINT ux_credential_disclosures_user_key_version UNIQUE (user_id, question_key, question_version);

ALTER TABLE ONLY platform.credential_licenses
    ADD CONSTRAINT ux_credential_licenses_user_state_number UNIQUE (user_id, state, license_number);

CREATE INDEX idx_practices_deleted_at ON platform.practices USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);

CREATE INDEX idx_practices_offboard_scheduled_at ON platform.practices USING btree (offboard_scheduled_at) WHERE (offboard_scheduled_at IS NOT NULL);

CREATE INDEX ix_credential_bank_accounts_user_id ON platform.credential_bank_accounts USING btree (user_id);

CREATE INDEX ix_credential_education_user_id ON platform.credential_education USING btree (user_id);

CREATE INDEX ix_credential_employment_user_id ON platform.credential_employment USING btree (user_id);

CREATE INDEX ix_credential_liability_policies_user_id ON platform.credential_liability_policies USING btree (user_id);

CREATE INDEX ix_credential_licenses_user_id ON platform.credential_licenses USING btree (user_id);

CREATE INDEX ix_credential_references_user_id ON platform.credential_references USING btree (user_id);

CREATE INDEX ix_credential_service_locations_user_id ON platform.credential_service_locations USING btree (user_id);

CREATE INDEX ix_credential_training_user_id ON platform.credential_training USING btree (user_id);

CREATE INDEX ix_diagnostic_definitions_code_active ON platform.diagnostic_definitions USING btree (code, active);

CREATE INDEX ix_panel_applications_practice_id ON platform.panel_applications USING btree (practice_id);

CREATE INDEX ix_panel_applications_user_id ON platform.panel_applications USING btree (user_id);

CREATE INDEX ix_platform_booking_links_user_id ON platform.booking_links USING btree (user_id);

CREATE INDEX ix_platform_claim_routes_practice_id ON platform.claim_routes USING btree (practice_id);

CREATE INDEX ix_platform_companion_devices_jkt ON platform.companion_devices USING btree (jkt);

CREATE INDEX ix_platform_companion_devices_user_id ON platform.companion_devices USING btree (user_id);

CREATE INDEX ix_platform_credential_bank_accounts_practice_id ON platform.credential_bank_accounts USING btree (practice_id);

CREATE INDEX ix_platform_credential_liability_policies_practice_id ON platform.credential_liability_policies USING btree (practice_id);

CREATE INDEX ix_platform_credential_licenses_practice_id ON platform.credential_licenses USING btree (practice_id);

CREATE INDEX ix_platform_launch_intents_expires_at ON platform.launch_intents USING btree (expires_at);

CREATE INDEX ix_platform_launch_intents_user_id ON platform.launch_intents USING btree (user_id);

CREATE INDEX ix_platform_passkey_backup_codes_user_id ON platform.passkey_backup_codes USING btree (user_id);

CREATE INDEX ix_platform_passkey_challenges_expires_at ON platform.passkey_challenges USING btree (expires_at);

CREATE INDEX ix_platform_passkey_challenges_user_id ON platform.passkey_challenges USING btree (user_id);

CREATE INDEX ix_platform_passkey_credentials_user_id ON platform.passkey_credentials USING btree (user_id);

CREATE INDEX ix_platform_platform_audit_logs_action ON platform.platform_audit_logs USING btree (action);

CREATE INDEX ix_platform_platform_audit_logs_actor_user_id ON platform.platform_audit_logs USING btree (actor_user_id);

CREATE INDEX ix_platform_platform_audit_logs_tenant_schema ON platform.platform_audit_logs USING btree (tenant_schema);

CREATE INDEX ix_platform_platform_audit_logs_timestamp ON platform.platform_audit_logs USING btree ("timestamp");

CREATE INDEX ix_platform_user_identities_user_id ON platform.user_identities USING btree (user_id);

CREATE UNIQUE INDEX ux_credential_liability_policies_one_current ON platform.credential_liability_policies USING btree (user_id) WHERE is_current;

CREATE UNIQUE INDEX ux_credential_licenses_one_primary ON platform.credential_licenses USING btree (user_id) WHERE is_primary;

CREATE UNIQUE INDEX ux_credential_service_locations_one_primary ON platform.credential_service_locations USING btree (user_id) WHERE is_primary;

CREATE TRIGGER practices_pentest_immutable BEFORE UPDATE OF is_pentest ON platform.practices FOR EACH ROW EXECUTE FUNCTION platform.practices_pentest_immutable();

ALTER TABLE ONLY platform.booking_links
    ADD CONSTRAINT booking_links_practice_id_fkey FOREIGN KEY (practice_id) REFERENCES platform.practices(id) ON DELETE CASCADE;

ALTER TABLE ONLY platform.companion_devices
    ADD CONSTRAINT companion_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES platform.users(id) ON DELETE CASCADE;

ALTER TABLE platform.credential_bank_accounts ENABLE ROW LEVEL SECURITY;

ALTER TABLE platform.credential_confirmations ENABLE ROW LEVEL SECURITY;

ALTER TABLE platform.credential_disclosures ENABLE ROW LEVEL SECURITY;

ALTER TABLE platform.credential_education ENABLE ROW LEVEL SECURITY;

ALTER TABLE platform.credential_employment ENABLE ROW LEVEL SECURITY;

ALTER TABLE platform.credential_government_ids ENABLE ROW LEVEL SECURITY;

ALTER TABLE platform.credential_liability_policies ENABLE ROW LEVEL SECURITY;

ALTER TABLE platform.credential_licenses ENABLE ROW LEVEL SECURITY;

ALTER TABLE platform.credential_references ENABLE ROW LEVEL SECURITY;

ALTER TABLE platform.credential_service_locations ENABLE ROW LEVEL SECURITY;

ALTER TABLE platform.credential_training ENABLE ROW LEVEL SECURITY;

ALTER TABLE platform.panel_applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY rls_credential_owner ON platform.credential_bank_accounts USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));

CREATE POLICY rls_credential_owner ON platform.credential_confirmations USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));

CREATE POLICY rls_credential_owner ON platform.credential_disclosures USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));

CREATE POLICY rls_credential_owner ON platform.credential_education USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));

CREATE POLICY rls_credential_owner ON platform.credential_employment USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));

CREATE POLICY rls_credential_owner ON platform.credential_government_ids USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));

CREATE POLICY rls_credential_owner ON platform.credential_liability_policies USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));

CREATE POLICY rls_credential_owner ON platform.credential_licenses USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));

CREATE POLICY rls_credential_owner ON platform.credential_references USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));

CREATE POLICY rls_credential_owner ON platform.credential_service_locations USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));

CREATE POLICY rls_credential_owner ON platform.credential_training USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));

CREATE POLICY rls_panel_application_owner ON platform.panel_applications USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((user_id)::text = current_setting('app.current_user_id'::text, true)));
