-- Auto-generated by backend/scripts/regen_tenant_template.py.
-- DO NOT EDIT MANUALLY.
--
-- Canonical schema for a freshly-provisioned tenant. Applied by
-- app.db.provisioning.create_practice_schema after the target schema
-- has been created. The placeholder __TENANT_SCHEMA__ is substituted
-- with the real schema name before execution.
--
-- Regenerate after any alembic revision that touches DDL:
--   poetry run python backend/scripts/regen_tenant_template.py









CREATE FUNCTION __TENANT_SCHEMA__.audit_logs_append_only() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF current_setting('app.allow_audit_purge', true) = 'on' THEN
                RETURN COALESCE(OLD, NEW);
            END IF;
            RAISE EXCEPTION USING
                MESSAGE = 'audit_logs is append-only (' || TG_OP || ' blocked)',
                ERRCODE = 'check_violation';
        END;
        $$;



CREATE FUNCTION __TENANT_SCHEMA__.audit_logs_no_truncate() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
        BEGIN
            IF current_setting('app.allow_audit_purge', true) = 'on' THEN
                RETURN NULL;
            END IF;
            RAISE EXCEPTION USING
                MESSAGE = 'audit_logs is append-only (TRUNCATE blocked)',
                ERRCODE = 'check_violation';
        END;
        $$;



CREATE FUNCTION __TENANT_SCHEMA__.has_patient_access(p_patient_id uuid, p_user_id character varying) RETURNS boolean
    LANGUAGE sql STABLE
    AS $$
        SELECT EXISTS (
            SELECT 1 FROM patient_clinicians
            WHERE patient_id = p_patient_id
              AND user_id::text = p_user_id
              AND (expires_at IS NULL OR expires_at > now())
        );
    $$;




CREATE TABLE __TENANT_SCHEMA__.alembic_version (
    version_num character varying(32) NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.allowed_emails (
    email character varying(255) NOT NULL,
    added_by character varying(255) NOT NULL,
    added_at timestamp with time zone NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.appointment_types (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    default_fee_cents integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    duration_minutes integer DEFAULT 50 NOT NULL,
    audience character varying(10) DEFAULT 'existing'::character varying NOT NULL,
    min_notice_hours integer,
    earliest_offer_business_days integer DEFAULT 1 NOT NULL,
    horizon integer DEFAULT 10 NOT NULL,
    horizon_unit character varying(10) DEFAULT 'business'::character varying NOT NULL,
    self_bookable boolean DEFAULT false NOT NULL,
    offerable boolean DEFAULT true NOT NULL,
    CONSTRAINT ck_appointment_types_audience CHECK (((audience)::text = ANY ((ARRAY['new'::character varying, 'existing'::character varying, 'both'::character varying])::text[]))),
    CONSTRAINT ck_appointment_types_duration CHECK (((duration_minutes >= 5) AND (duration_minutes <= 480))),
    CONSTRAINT ck_appointment_types_earliest_offer CHECK ((earliest_offer_business_days >= 0)),
    CONSTRAINT ck_appointment_types_horizon CHECK ((horizon > 0)),
    CONSTRAINT ck_appointment_types_horizon_unit CHECK (((horizon_unit)::text = ANY ((ARRAY['business'::character varying, 'days'::character varying])::text[]))),
    CONSTRAINT ck_appointment_types_min_notice CHECK (((min_notice_hours IS NULL) OR (min_notice_hours >= 0)))
);



CREATE TABLE __TENANT_SCHEMA__.appointments (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    start_at timestamp with time zone NOT NULL,
    end_at timestamp with time zone NOT NULL,
    duration_minutes integer NOT NULL,
    status character varying(20) NOT NULL,
    session_type character varying(30) NOT NULL,
    video_link text,
    video_platform character varying(30),
    notes text,
    recurrence_rule character varying(50),
    recurring_appointment_id uuid,
    recurrence_index integer,
    is_exception boolean NOT NULL,
    google_event_id character varying(255),
    google_calendar_id character varying(255),
    google_sync_status character varying(20),
    ical_uid character varying(255),
    ical_source character varying(50),
    ical_sync_status character varying(20),
    ehr_appointment_url text,
    session_id uuid,
    reminder_24h_sent boolean NOT NULL,
    reminder_1h_sent boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    pending_expires_at timestamp with time zone,
    service_code character varying(10),
    modifiers jsonb,
    unit_count integer,
    place_of_service character varying(2),
    diagnosis_codes jsonb,
    note_type character varying(30) DEFAULT 'soap'::character varying NOT NULL,
    confirmation_token_hash character varying(64),
    appointment_type_id uuid
);



CREATE TABLE __TENANT_SCHEMA__.audit_logs (
    id uuid NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    user_id character varying(128) NOT NULL,
    action character varying(50) NOT NULL,
    resource_type character varying(30) NOT NULL,
    resource_id character varying(128) NOT NULL,
    patient_id uuid,
    session_id uuid,
    ip_address character varying(45),
    user_agent text,
    changes jsonb,
    actor_type character varying(20) DEFAULT 'clinician'::character varying NOT NULL,
    actor_component character varying(64),
    CONSTRAINT audit_logs_user_id_not_empty CHECK (((user_id)::text <> ''::text))
);



CREATE TABLE __TENANT_SCHEMA__.availability_rules (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    rule_type character varying(30) NOT NULL,
    enforcement character varying(10) NOT NULL,
    params jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone
);



CREATE TABLE __TENANT_SCHEMA__.chat_conversations (
    id uuid NOT NULL,
    patient_id uuid NOT NULL,
    owner_user_id uuid NOT NULL,
    title character varying(200) NOT NULL,
    caller_system_prompt text NOT NULL,
    caller_feature_key character varying(64) NOT NULL,
    default_source_selection jsonb,
    created_at timestamp with time zone NOT NULL,
    last_turn_at timestamp with time zone,
    archived_at timestamp with time zone,
    CONSTRAINT ck_chat_conversations_system_prompt_len CHECK (((char_length(caller_system_prompt) >= 1) AND (char_length(caller_system_prompt) <= 16384))),
    CONSTRAINT ck_chat_conversations_title_len CHECK (((char_length((title)::text) >= 1) AND (char_length((title)::text) <= 200)))
);



CREATE TABLE __TENANT_SCHEMA__.chat_messages (
    id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    sequence integer NOT NULL,
    role character varying(16) NOT NULL,
    content text NOT NULL,
    source_selection jsonb,
    context_manifest jsonb,
    input_tokens integer,
    output_tokens integer,
    llm_model character varying(128),
    llm_finish_reason character varying(32),
    llm_error character varying(128),
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_chat_messages_content_len CHECK (((char_length(content) >= 0) AND (char_length(content) <= 32768))),
    CONSTRAINT ck_chat_messages_role CHECK (((role)::text = ANY ((ARRAY['user'::character varying, 'assistant'::character varying])::text[])))
);



CREATE TABLE __TENANT_SCHEMA__.clinician_profiles (
    user_id uuid NOT NULL,
    practice_id character varying(128) NOT NULL,
    title character varying(50),
    credentials character varying(100),
    role character varying(20) DEFAULT 'clinician'::character varying NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    license_number character varying(100),
    license_state character varying(2),
    dea_number character varying(50),
    npi_number character varying(20),
    credential_titles jsonb
);



CREATE TABLE __TENANT_SCHEMA__.compliance_documents (
    id uuid NOT NULL,
    compliance_item_id uuid,
    filename character varying(255) NOT NULL,
    mime_type character varying(100) NOT NULL,
    size_bytes bigint NOT NULL,
    storage_uri text NOT NULL,
    document_type character varying(50) NOT NULL,
    description text,
    uploaded_at timestamp with time zone NOT NULL,
    uploaded_by_user_id uuid NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.compliance_items (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    item_type character varying(50) NOT NULL,
    label character varying(255) NOT NULL,
    due_date date,
    notes text,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.diagnostic_assessments (
    id uuid NOT NULL,
    patient_id uuid NOT NULL,
    session_id uuid,
    appointment_id uuid,
    instrument character varying(40) NOT NULL,
    definition_version integer NOT NULL,
    criterion_responses jsonb NOT NULL,
    gate_responses jsonb NOT NULL,
    meets_criteria boolean,
    determined_icd10 character varying(10),
    diagnosis_label character varying(120),
    criterion_citations jsonb,
    source character varying(40) NOT NULL,
    confirmed_at timestamp with time zone,
    assessed_at timestamp with time zone NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT ck_diagnostic_assessments_source CHECK (((source)::text = ANY ((ARRAY['patient_self_report'::character varying, 'clinician_administered_verbal'::character varying, 'manual'::character varying, 'inferred'::character varying])::text[])))
);



CREATE TABLE __TENANT_SCHEMA__.ehr_prompts (
    ehr_system character varying(50) NOT NULL,
    system_prompt text NOT NULL,
    version integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    updated_by character varying(255) NOT NULL,
    notes text NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.ehr_routes (
    id character varying(50) NOT NULL,
    ehr_system character varying(50) NOT NULL,
    route_name character varying(255) NOT NULL,
    steps jsonb NOT NULL,
    success_count integer NOT NULL,
    last_success timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.google_calendar_tokens (
    user_id uuid NOT NULL,
    encrypted_tokens text NOT NULL,
    calendar_id character varying(255),
    sync_token text,
    last_synced_at timestamp with time zone,
    connected_at timestamp with time zone,
    consecutive_error_count integer DEFAULT 0,
    last_sync_error text,
    provider character varying(32) DEFAULT 'google'::character varying NOT NULL,
    write_target character varying(32) DEFAULT 'primary'::character varying NOT NULL,
    granted_capabilities character varying(255) DEFAULT 'push,import'::character varying NOT NULL,
    event_titling character varying(16) DEFAULT 'generic'::character varying NOT NULL,
    titling_attested_account character varying(255) DEFAULT ''::character varying NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.ical_client_mappings (
    doc_id character varying(500) NOT NULL,
    user_id uuid NOT NULL,
    ehr_system character varying(50) NOT NULL,
    client_identifier character varying(255) NOT NULL,
    patient_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.ical_sync_configs (
    doc_id character varying(300) NOT NULL,
    user_id uuid NOT NULL,
    ehr_system character varying(50) NOT NULL,
    encrypted_feed_url text NOT NULL,
    last_synced_at timestamp with time zone,
    last_sync_error text,
    connected_at timestamp with time zone NOT NULL,
    consecutive_error_count integer DEFAULT 0
);



CREATE TABLE __TENANT_SCHEMA__.llm_usage (
    user_id uuid NOT NULL,
    feature_key character varying(64) NOT NULL,
    period_yyyymm character varying(6) NOT NULL,
    model character varying(128) NOT NULL,
    input_tokens bigint DEFAULT '0'::bigint NOT NULL,
    output_tokens bigint DEFAULT '0'::bigint NOT NULL,
    turn_count bigint DEFAULT '0'::bigint NOT NULL,
    first_recorded_at timestamp with time zone NOT NULL,
    last_recorded_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_llm_usage_nonneg CHECK (((input_tokens >= 0) AND (output_tokens >= 0) AND (turn_count >= 0))),
    CONSTRAINT ck_llm_usage_period_yyyymm_shape CHECK (((period_yyyymm)::text ~ '^[0-9]{6}$'::text))
);



CREATE TABLE __TENANT_SCHEMA__.notes (
    id uuid NOT NULL,
    patient_id uuid NOT NULL,
    session_id uuid,
    note_type character varying(30) DEFAULT 'soap'::character varying NOT NULL,
    content jsonb,
    content_edited jsonb,
    finalized_at timestamp with time zone,
    quality_rating integer,
    quality_rating_reason text,
    quality_rating_sections jsonb,
    export_status character varying(20) DEFAULT 'not_queued'::character varying NOT NULL,
    export_queued_at timestamp with time zone,
    export_reviewed_at timestamp with time zone,
    export_reviewed_by uuid,
    exported_at timestamp with time zone,
    redacted_content jsonb,
    naturalized_content jsonb,
    redacted_export_payload jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    status character varying(20) DEFAULT 'complete'::character varying NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.outcome_measures (
    id uuid NOT NULL,
    patient_id uuid NOT NULL,
    session_id uuid,
    appointment_id uuid,
    instrument character varying(20) NOT NULL,
    total_score integer,
    item_scores jsonb,
    is_complete boolean DEFAULT false NOT NULL,
    source character varying(40) NOT NULL,
    item_citations jsonb,
    administered_at timestamp with time zone NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT ck_outcome_measures_source CHECK (((source)::text = ANY ((ARRAY['patient_self_report'::character varying, 'clinician_administered_verbal'::character varying, 'manual'::character varying, 'inferred'::character varying])::text[])))
);



CREATE TABLE __TENANT_SCHEMA__.patient_clinicians (
    patient_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role character varying(20) DEFAULT 'primary'::character varying NOT NULL,
    granted_at timestamp with time zone DEFAULT now() NOT NULL,
    granted_by uuid NOT NULL,
    expires_at timestamp with time zone,
    CONSTRAINT patient_clinicians_role_check CHECK (((role)::text = ANY ((ARRAY['primary'::character varying, 'co_treating'::character varying, 'supervisor'::character varying, 'covering'::character varying])::text[])))
);



CREATE TABLE __TENANT_SCHEMA__.patient_documents (
    id uuid NOT NULL,
    patient_id uuid NOT NULL,
    user_id uuid NOT NULL,
    filename text NOT NULL,
    mime_type character varying(100) NOT NULL,
    gcs_path text NOT NULL,
    extracted_text text,
    size_bytes bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    finalized_at timestamp with time zone,
    deleted_at timestamp with time zone,
    category character varying(32) DEFAULT 'chart'::character varying NOT NULL,
    extracted_via character varying(32),
    extraction_metadata jsonb,
    extraction_status character varying(16),
    CONSTRAINT ck_patient_documents_category CHECK (((category)::text = ANY ((ARRAY['chart'::character varying, 'consent'::character varying, 'therapist_private'::character varying, 'psychotherapy_notes'::character varying])::text[]))),
    CONSTRAINT ck_patient_documents_extracted_via CHECK (((extracted_via IS NULL) OR ((extracted_via)::text = ANY ((ARRAY['pymupdf'::character varying, 'document_ai'::character varying, 'unavailable'::character varying])::text[])))),
    CONSTRAINT ck_patient_documents_extraction_status CHECK (((extraction_status IS NULL) OR ((extraction_status)::text = ANY ((ARRAY['pending'::character varying, 'complete'::character varying, 'failed'::character varying])::text[]))))
);



CREATE TABLE __TENANT_SCHEMA__.patient_medications (
    id uuid NOT NULL,
    patient_id uuid NOT NULL,
    drug_name character varying(200) NOT NULL,
    dose character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    started_at date,
    stopped_at date,
    notes text,
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    stop_reason text,
    CONSTRAINT ck_patient_medications_status CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'discontinued'::character varying, 'on_hold'::character varying])::text[])))
);



CREATE TABLE __TENANT_SCHEMA__.patients (
    id uuid NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    first_name_lower character varying(255) NOT NULL,
    last_name_lower character varying(255) NOT NULL,
    email character varying(255),
    phone character varying(50),
    status character varying(20) NOT NULL,
    date_of_birth date,
    diagnosis text,
    session_count integer NOT NULL,
    last_session_date timestamp with time zone,
    next_session_date timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    chart_closed_at timestamp with time zone,
    chart_closure_reason text,
    phi_email_consent boolean,
    phi_email_consent_at timestamp with time zone,
    phi_email_consent_doc text,
    phi_email_consent_by character varying(128),
    rate_cents integer,
    sliding_scale_note text,
    origin character varying(20)
);



CREATE TABLE __TENANT_SCHEMA__.prescribing_checklist_items (
    id uuid NOT NULL,
    encounter_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    item_id character varying(120) NOT NULL,
    requirement_level character varying(20) NOT NULL,
    flag_behavior character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    evidence_link character varying(512),
    captured_by uuid,
    captured_at timestamp with time zone,
    authority_ref character varying(255),
    ruleset_version character varying(40) NOT NULL,
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT ck_prescribing_checklist_items_flag_behavior CHECK (((flag_behavior)::text = ANY ((ARRAY['hard_stop'::character varying, 'soft_warn'::character varying, 'info'::character varying])::text[]))),
    CONSTRAINT ck_prescribing_checklist_items_requirement_level CHECK (((requirement_level)::text = ANY ((ARRAY['required'::character varying, 'conditional'::character varying, 'recommended'::character varying])::text[]))),
    CONSTRAINT ck_prescribing_checklist_items_status CHECK (((status)::text = ANY ((ARRAY['satisfied'::character varying, 'missing'::character varying, 'na'::character varying])::text[])))
);



CREATE TABLE __TENANT_SCHEMA__.prescribing_encounter_addenda (
    id uuid NOT NULL,
    encounter_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    label character varying(120) NOT NULL,
    text text NOT NULL,
    digest character varying(64) NOT NULL,
    prev_digest character varying(64),
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.prescribing_encounters (
    id uuid NOT NULL,
    patient_id uuid NOT NULL,
    prescriber_user_id uuid NOT NULL,
    prescriber_type character varying(40),
    prescriber_npi character varying(20),
    prescriber_dea character varying(50),
    prescriber_license character varying(100),
    delegation_ref character varying(128),
    delegating_physician_name character varying(255),
    delegating_physician_dea character varying(50),
    state character varying(2),
    modality character varying(20),
    prior_in_person boolean,
    patient_in_sud_program boolean,
    ruleset_version character varying(40),
    status character varying(20) NOT NULL,
    encountered_at timestamp with time zone,
    finalized_at timestamp with time zone,
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    integrity_digest character varying(64),
    finalized_by uuid,
    attestation_statement text,
    clinical_reasoning text,
    requires_delegation boolean,
    CONSTRAINT ck_prescribing_encounters_modality CHECK (((modality IS NULL) OR ((modality)::text = ANY ((ARRAY['in_person'::character varying, 'audio_video'::character varying, 'audio_only'::character varying, 'async'::character varying])::text[])))),
    CONSTRAINT ck_prescribing_encounters_status CHECK (((status)::text = ANY ((ARRAY['open'::character varying, 'finalized'::character varying, 'voided'::character varying])::text[])))
);



CREATE TABLE __TENANT_SCHEMA__.prescriptions (
    id uuid NOT NULL,
    encounter_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    rxnorm_id character varying(20),
    drug_name character varying(200),
    schedule character varying(4) NOT NULL,
    drug_class character varying(20) NOT NULL,
    strength character varying(100),
    quantity integer,
    days_supply integer,
    refills integer NOT NULL,
    indication character varying(40),
    first_in_course boolean,
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT ck_prescriptions_drug_class CHECK (((drug_class)::text = ANY ((ARRAY['opioid'::character varying, 'stimulant'::character varying, 'benzodiazepine'::character varying, 'buprenorphine'::character varying, 'other'::character varying])::text[]))),
    CONSTRAINT ck_prescriptions_schedule CHECK (((schedule)::text = ANY ((ARRAY['II'::character varying, 'III'::character varying, 'IV'::character varying, 'V'::character varying, 'none'::character varying])::text[])))
);



CREATE TABLE __TENANT_SCHEMA__.scheduling_policy (
    id smallint NOT NULL,
    min_notice_hours integer DEFAULT 24 NOT NULL,
    max_horizon_days integer DEFAULT 60 NOT NULL,
    cancel_cutoff_hours integer DEFAULT 24 NOT NULL,
    reschedule_cutoff_hours integer DEFAULT 24 NOT NULL,
    pending_hold_hours integer DEFAULT 72 NOT NULL,
    self_book_existing boolean DEFAULT false NOT NULL,
    self_book_new boolean DEFAULT false NOT NULL,
    self_book_mode character varying(10) DEFAULT 'request'::character varying NOT NULL,
    new_patient_flow character varying(10) DEFAULT 'consult'::character varying NOT NULL,
    intake_forms_due_hours integer DEFAULT 48 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ck_scheduling_policy_cancel_cutoff CHECK ((cancel_cutoff_hours >= 0)),
    CONSTRAINT ck_scheduling_policy_intake_forms_due CHECK ((intake_forms_due_hours >= 0)),
    CONSTRAINT ck_scheduling_policy_max_horizon CHECK ((max_horizon_days > 0)),
    CONSTRAINT ck_scheduling_policy_min_notice CHECK ((min_notice_hours >= 0)),
    CONSTRAINT ck_scheduling_policy_new_patient_flow CHECK (((new_patient_flow)::text = ANY ((ARRAY['consult'::character varying, 'intake'::character varying])::text[]))),
    CONSTRAINT ck_scheduling_policy_pending_hold CHECK ((pending_hold_hours > 0)),
    CONSTRAINT ck_scheduling_policy_reschedule_cutoff CHECK ((reschedule_cutoff_hours >= 0)),
    CONSTRAINT ck_scheduling_policy_self_book_mode CHECK (((self_book_mode)::text = ANY ((ARRAY['request'::character varying, 'auto'::character varying])::text[]))),
    CONSTRAINT ck_scheduling_policy_singleton CHECK ((id = 1))
);



CREATE SEQUENCE __TENANT_SCHEMA__.scheduling_policy_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE __TENANT_SCHEMA__.scheduling_policy_id_seq OWNED BY __TENANT_SCHEMA__.scheduling_policy.id;



CREATE TABLE __TENANT_SCHEMA__.supervision_hours (
    id uuid NOT NULL,
    supervision_relationship_id uuid NOT NULL,
    user_id uuid NOT NULL,
    logged_date date NOT NULL,
    hours numeric(6,2) NOT NULL,
    kind character varying(20) NOT NULL,
    supervisor character varying(255),
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.supervision_relationships (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    compliance_item_id uuid,
    relationship_type character varying(50) NOT NULL,
    supervisor_name character varying(255) NOT NULL,
    supervisor_credential character varying(100),
    supervisor_dea character varying(50),
    supervisor_license character varying(100),
    state character varying(2),
    effective_date date,
    review_cadence_days integer,
    next_review_date date,
    authority_ref character varying(255),
    status character varying(20) NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);



CREATE TABLE __TENANT_SCHEMA__.therapy_sessions (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    patient_id uuid NOT NULL,
    session_date timestamp with time zone NOT NULL,
    session_number integer NOT NULL,
    status character varying(30) NOT NULL,
    transcript jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    scheduled_at timestamp with time zone,
    video_link text,
    video_platform character varying(30),
    session_type character varying(30),
    duration_minutes integer,
    source character varying(30),
    notes text,
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    updated_at timestamp with time zone,
    audio_gcs_path text,
    processing_started_at timestamp with time zone,
    processing_completed_at timestamp with time zone,
    error text,
    redacted_transcript text,
    naturalized_transcript text,
    deleted_at timestamp with time zone,
    transcription_job_metadata jsonb
);



ALTER TABLE ONLY __TENANT_SCHEMA__.scheduling_policy ALTER COLUMN id SET DEFAULT nextval('__TENANT_SCHEMA__.scheduling_policy_id_seq'::regclass);



ALTER TABLE ONLY __TENANT_SCHEMA__.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);



ALTER TABLE ONLY __TENANT_SCHEMA__.allowed_emails
    ADD CONSTRAINT allowed_emails_pkey PRIMARY KEY (email);



ALTER TABLE ONLY __TENANT_SCHEMA__.appointment_types
    ADD CONSTRAINT appointment_types_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.availability_rules
    ADD CONSTRAINT availability_rules_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.chat_conversations
    ADD CONSTRAINT chat_conversations_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.clinician_profiles
    ADD CONSTRAINT clinician_profiles_pkey PRIMARY KEY (user_id);



ALTER TABLE ONLY __TENANT_SCHEMA__.compliance_documents
    ADD CONSTRAINT compliance_documents_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.compliance_items
    ADD CONSTRAINT compliance_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.diagnostic_assessments
    ADD CONSTRAINT diagnostic_assessments_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.ehr_prompts
    ADD CONSTRAINT ehr_prompts_pkey PRIMARY KEY (ehr_system);



ALTER TABLE ONLY __TENANT_SCHEMA__.ehr_routes
    ADD CONSTRAINT ehr_routes_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.google_calendar_tokens
    ADD CONSTRAINT google_calendar_tokens_pkey PRIMARY KEY (user_id);



ALTER TABLE ONLY __TENANT_SCHEMA__.ical_client_mappings
    ADD CONSTRAINT ical_client_mappings_pkey PRIMARY KEY (doc_id);



ALTER TABLE ONLY __TENANT_SCHEMA__.ical_sync_configs
    ADD CONSTRAINT ical_sync_configs_pkey PRIMARY KEY (doc_id);



ALTER TABLE ONLY __TENANT_SCHEMA__.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.outcome_measures
    ADD CONSTRAINT outcome_measures_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.patient_clinicians
    ADD CONSTRAINT patient_clinicians_pkey PRIMARY KEY (patient_id, user_id);



ALTER TABLE ONLY __TENANT_SCHEMA__.patient_documents
    ADD CONSTRAINT patient_documents_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.patient_medications
    ADD CONSTRAINT patient_medications_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.patients
    ADD CONSTRAINT patients_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.llm_usage
    ADD CONSTRAINT pk_llm_usage PRIMARY KEY (user_id, feature_key, period_yyyymm, model);



ALTER TABLE ONLY __TENANT_SCHEMA__.prescribing_checklist_items
    ADD CONSTRAINT prescribing_checklist_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.prescribing_encounter_addenda
    ADD CONSTRAINT prescribing_encounter_addenda_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.prescribing_encounters
    ADD CONSTRAINT prescribing_encounters_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.prescriptions
    ADD CONSTRAINT prescriptions_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.scheduling_policy
    ADD CONSTRAINT scheduling_policy_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.supervision_hours
    ADD CONSTRAINT supervision_hours_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.supervision_relationships
    ADD CONSTRAINT supervision_relationships_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.therapy_sessions
    ADD CONSTRAINT therapy_sessions_pkey PRIMARY KEY (id);



ALTER TABLE ONLY __TENANT_SCHEMA__.appointment_types
    ADD CONSTRAINT uq_appointment_types_user_name UNIQUE (user_id, name);



ALTER TABLE ONLY __TENANT_SCHEMA__.prescribing_checklist_items
    ADD CONSTRAINT uq_prescribing_checklist_items_encounter_item UNIQUE (encounter_id, item_id);



CREATE INDEX ix_appointment_types_user_id ON __TENANT_SCHEMA__.appointment_types USING btree (user_id);



CREATE INDEX ix_appointments_appointment_type_id ON __TENANT_SCHEMA__.appointments USING btree (appointment_type_id);



CREATE INDEX ix_appointments_confirmation_token_hash ON __TENANT_SCHEMA__.appointments USING btree (confirmation_token_hash) WHERE (confirmation_token_hash IS NOT NULL);



CREATE INDEX ix_appointments_ical_source ON __TENANT_SCHEMA__.appointments USING btree (ical_source);



CREATE INDEX ix_appointments_patient_id ON __TENANT_SCHEMA__.appointments USING btree (patient_id);



CREATE INDEX ix_appointments_pending_expires_at ON __TENANT_SCHEMA__.appointments USING btree (pending_expires_at) WHERE (pending_expires_at IS NOT NULL);



CREATE INDEX ix_appointments_recurring_appointment_id ON __TENANT_SCHEMA__.appointments USING btree (recurring_appointment_id);



CREATE INDEX ix_appointments_start_at ON __TENANT_SCHEMA__.appointments USING btree (start_at);



CREATE INDEX ix_appointments_user_id ON __TENANT_SCHEMA__.appointments USING btree (user_id);



CREATE INDEX ix_audit_logs_action ON __TENANT_SCHEMA__.audit_logs USING btree (action);



CREATE INDEX ix_audit_logs_actor_type ON __TENANT_SCHEMA__.audit_logs USING btree (actor_type);



CREATE INDEX ix_audit_logs_patient_id ON __TENANT_SCHEMA__.audit_logs USING btree (patient_id);



CREATE INDEX ix_audit_logs_timestamp ON __TENANT_SCHEMA__.audit_logs USING btree ("timestamp");



CREATE INDEX ix_audit_logs_user_id ON __TENANT_SCHEMA__.audit_logs USING btree (user_id);



CREATE INDEX ix_audit_logs_user_timestamp ON __TENANT_SCHEMA__.audit_logs USING btree (user_id, "timestamp" DESC);



CREATE INDEX ix_availability_rules_user_id ON __TENANT_SCHEMA__.availability_rules USING btree (user_id);



CREATE INDEX ix_chat_conversations_caller_feature_key ON __TENANT_SCHEMA__.chat_conversations USING btree (caller_feature_key);



CREATE INDEX ix_chat_conversations_owner_last_turn ON __TENANT_SCHEMA__.chat_conversations USING btree (owner_user_id, last_turn_at);



CREATE INDEX ix_chat_conversations_owner_user_id ON __TENANT_SCHEMA__.chat_conversations USING btree (owner_user_id);



CREATE INDEX ix_chat_conversations_patient_id ON __TENANT_SCHEMA__.chat_conversations USING btree (patient_id);



CREATE INDEX ix_chat_conversations_patient_last_turn ON __TENANT_SCHEMA__.chat_conversations USING btree (patient_id, last_turn_at);



CREATE INDEX ix_chat_messages_conversation_id ON __TENANT_SCHEMA__.chat_messages USING btree (conversation_id);



CREATE INDEX ix_compliance_documents_compliance_item_id ON __TENANT_SCHEMA__.compliance_documents USING btree (compliance_item_id);



CREATE INDEX ix_compliance_documents_uploaded_by_user_id ON __TENANT_SCHEMA__.compliance_documents USING btree (uploaded_by_user_id);



CREATE INDEX ix_compliance_items_user_id ON __TENANT_SCHEMA__.compliance_items USING btree (user_id);



CREATE INDEX ix_diagnostic_assessments_appointment_id ON __TENANT_SCHEMA__.diagnostic_assessments USING btree (appointment_id);



CREATE INDEX ix_diagnostic_assessments_patient_id ON __TENANT_SCHEMA__.diagnostic_assessments USING btree (patient_id);



CREATE INDEX ix_diagnostic_assessments_patient_instrument_assessed ON __TENANT_SCHEMA__.diagnostic_assessments USING btree (patient_id, instrument, assessed_at);



CREATE INDEX ix_diagnostic_assessments_session_id ON __TENANT_SCHEMA__.diagnostic_assessments USING btree (session_id);



CREATE INDEX ix_ehr_routes_ehr_system ON __TENANT_SCHEMA__.ehr_routes USING btree (ehr_system);



CREATE INDEX ix_ical_client_mappings_user_id ON __TENANT_SCHEMA__.ical_client_mappings USING btree (user_id);



CREATE INDEX ix_ical_sync_configs_user_id ON __TENANT_SCHEMA__.ical_sync_configs USING btree (user_id);



CREATE INDEX ix_llm_usage_feature_period ON __TENANT_SCHEMA__.llm_usage USING btree (feature_key, period_yyyymm);



CREATE INDEX ix_llm_usage_period ON __TENANT_SCHEMA__.llm_usage USING btree (period_yyyymm);



CREATE INDEX ix_notes_deleted_at_partial ON __TENANT_SCHEMA__.notes USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);



CREATE INDEX ix_notes_patient_finalized ON __TENANT_SCHEMA__.notes USING btree (patient_id, finalized_at DESC);



CREATE INDEX ix_notes_patient_id ON __TENANT_SCHEMA__.notes USING btree (patient_id);



CREATE INDEX ix_notes_session_id ON __TENANT_SCHEMA__.notes USING btree (session_id);



CREATE INDEX ix_outcome_measures_appointment_id ON __TENANT_SCHEMA__.outcome_measures USING btree (appointment_id);



CREATE INDEX ix_outcome_measures_patient_id ON __TENANT_SCHEMA__.outcome_measures USING btree (patient_id);



CREATE INDEX ix_outcome_measures_patient_instrument_administered ON __TENANT_SCHEMA__.outcome_measures USING btree (patient_id, instrument, administered_at);



CREATE INDEX ix_outcome_measures_session_id ON __TENANT_SCHEMA__.outcome_measures USING btree (session_id);



CREATE INDEX ix_patient_clinicians_user_id ON __TENANT_SCHEMA__.patient_clinicians USING btree (user_id);



CREATE INDEX ix_patient_documents_patient_deleted ON __TENANT_SCHEMA__.patient_documents USING btree (patient_id, deleted_at);



CREATE INDEX ix_patient_documents_user_id ON __TENANT_SCHEMA__.patient_documents USING btree (user_id);



CREATE INDEX ix_patient_medications_patient_id ON __TENANT_SCHEMA__.patient_medications USING btree (patient_id);



CREATE INDEX ix_patient_medications_patient_status ON __TENANT_SCHEMA__.patient_medications USING btree (patient_id, status);



CREATE INDEX ix_patients_deleted_at_partial ON __TENANT_SCHEMA__.patients USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);



CREATE INDEX ix_patients_email_lower ON __TENANT_SCHEMA__.patients USING btree (lower((email)::text)) WHERE (deleted_at IS NULL);



CREATE INDEX ix_patients_first_name_lower ON __TENANT_SCHEMA__.patients USING btree (first_name_lower);



CREATE INDEX ix_patients_last_name_lower ON __TENANT_SCHEMA__.patients USING btree (last_name_lower);



CREATE INDEX ix_prescribing_checklist_items_encounter_id ON __TENANT_SCHEMA__.prescribing_checklist_items USING btree (encounter_id);



CREATE INDEX ix_prescribing_checklist_items_patient_id ON __TENANT_SCHEMA__.prescribing_checklist_items USING btree (patient_id);



CREATE INDEX ix_prescribing_encounter_addenda_encounter_id ON __TENANT_SCHEMA__.prescribing_encounter_addenda USING btree (encounter_id);



CREATE INDEX ix_prescribing_encounter_addenda_patient_id ON __TENANT_SCHEMA__.prescribing_encounter_addenda USING btree (patient_id);



CREATE INDEX ix_prescribing_encounters_patient_encountered ON __TENANT_SCHEMA__.prescribing_encounters USING btree (patient_id, encountered_at);



CREATE INDEX ix_prescribing_encounters_patient_id ON __TENANT_SCHEMA__.prescribing_encounters USING btree (patient_id);



CREATE INDEX ix_prescribing_encounters_prescriber_user_id ON __TENANT_SCHEMA__.prescribing_encounters USING btree (prescriber_user_id);



CREATE INDEX ix_prescriptions_encounter_id ON __TENANT_SCHEMA__.prescriptions USING btree (encounter_id);



CREATE INDEX ix_prescriptions_patient_id ON __TENANT_SCHEMA__.prescriptions USING btree (patient_id);



CREATE INDEX ix_supervision_hours_supervision_relationship_id ON __TENANT_SCHEMA__.supervision_hours USING btree (supervision_relationship_id);



CREATE INDEX ix_supervision_hours_user_id ON __TENANT_SCHEMA__.supervision_hours USING btree (user_id);



CREATE INDEX ix_supervision_relationships_compliance_item_id ON __TENANT_SCHEMA__.supervision_relationships USING btree (compliance_item_id);



CREATE INDEX ix_supervision_relationships_user_id ON __TENANT_SCHEMA__.supervision_relationships USING btree (user_id);



CREATE INDEX ix_therapy_sessions_deleted_at_partial ON __TENANT_SCHEMA__.therapy_sessions USING btree (deleted_at) WHERE (deleted_at IS NOT NULL);



CREATE INDEX ix_therapy_sessions_patient_id ON __TENANT_SCHEMA__.therapy_sessions USING btree (patient_id);



CREATE INDEX ix_therapy_sessions_scheduled_at ON __TENANT_SCHEMA__.therapy_sessions USING btree (scheduled_at);



CREATE INDEX ix_therapy_sessions_session_date ON __TENANT_SCHEMA__.therapy_sessions USING btree (session_date);



CREATE INDEX ix_therapy_sessions_user_id ON __TENANT_SCHEMA__.therapy_sessions USING btree (user_id);



CREATE UNIQUE INDEX uq_appointments_user_start_active ON __TENANT_SCHEMA__.appointments USING btree (user_id, start_at) WHERE ((status)::text <> 'cancelled'::text);



CREATE UNIQUE INDEX ux_chat_messages_conversation_sequence ON __TENANT_SCHEMA__.chat_messages USING btree (conversation_id, sequence);



CREATE UNIQUE INDEX ux_notes_session_id ON __TENANT_SCHEMA__.notes USING btree (session_id) WHERE (session_id IS NOT NULL);



CREATE TRIGGER audit_logs_append_only BEFORE DELETE OR UPDATE ON __TENANT_SCHEMA__.audit_logs FOR EACH ROW EXECUTE FUNCTION __TENANT_SCHEMA__.audit_logs_append_only();



CREATE TRIGGER audit_logs_no_truncate BEFORE TRUNCATE ON __TENANT_SCHEMA__.audit_logs FOR EACH STATEMENT EXECUTE FUNCTION __TENANT_SCHEMA__.audit_logs_no_truncate();



ALTER TABLE ONLY __TENANT_SCHEMA__.appointments
    ADD CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.appointments
    ADD CONSTRAINT appointments_recurring_appointment_id_fkey FOREIGN KEY (recurring_appointment_id) REFERENCES __TENANT_SCHEMA__.appointments(id) ON DELETE SET NULL;



ALTER TABLE ONLY __TENANT_SCHEMA__.appointments
    ADD CONSTRAINT appointments_session_id_fkey FOREIGN KEY (session_id) REFERENCES __TENANT_SCHEMA__.therapy_sessions(id) ON DELETE SET NULL;



ALTER TABLE ONLY __TENANT_SCHEMA__.chat_conversations
    ADD CONSTRAINT chat_conversations_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.chat_messages
    ADD CONSTRAINT chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES __TENANT_SCHEMA__.chat_conversations(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.compliance_documents
    ADD CONSTRAINT compliance_documents_compliance_item_id_fkey FOREIGN KEY (compliance_item_id) REFERENCES __TENANT_SCHEMA__.compliance_items(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.diagnostic_assessments
    ADD CONSTRAINT diagnostic_assessments_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES __TENANT_SCHEMA__.appointments(id) ON DELETE SET NULL;



ALTER TABLE ONLY __TENANT_SCHEMA__.diagnostic_assessments
    ADD CONSTRAINT diagnostic_assessments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.diagnostic_assessments
    ADD CONSTRAINT diagnostic_assessments_session_id_fkey FOREIGN KEY (session_id) REFERENCES __TENANT_SCHEMA__.therapy_sessions(id) ON DELETE SET NULL;



ALTER TABLE ONLY __TENANT_SCHEMA__.appointments
    ADD CONSTRAINT fk_appointments_appointment_type FOREIGN KEY (appointment_type_id) REFERENCES __TENANT_SCHEMA__.appointment_types(id) ON DELETE SET NULL;



ALTER TABLE ONLY __TENANT_SCHEMA__.ical_client_mappings
    ADD CONSTRAINT ical_client_mappings_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.notes
    ADD CONSTRAINT notes_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.notes
    ADD CONSTRAINT notes_session_id_fkey FOREIGN KEY (session_id) REFERENCES __TENANT_SCHEMA__.therapy_sessions(id) ON DELETE SET NULL;



ALTER TABLE ONLY __TENANT_SCHEMA__.outcome_measures
    ADD CONSTRAINT outcome_measures_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES __TENANT_SCHEMA__.appointments(id) ON DELETE SET NULL;



ALTER TABLE ONLY __TENANT_SCHEMA__.outcome_measures
    ADD CONSTRAINT outcome_measures_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.outcome_measures
    ADD CONSTRAINT outcome_measures_session_id_fkey FOREIGN KEY (session_id) REFERENCES __TENANT_SCHEMA__.therapy_sessions(id) ON DELETE SET NULL;



ALTER TABLE ONLY __TENANT_SCHEMA__.patient_clinicians
    ADD CONSTRAINT patient_clinicians_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.patient_documents
    ADD CONSTRAINT patient_documents_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.patient_medications
    ADD CONSTRAINT patient_medications_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.prescribing_checklist_items
    ADD CONSTRAINT prescribing_checklist_items_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES __TENANT_SCHEMA__.prescribing_encounters(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.prescribing_checklist_items
    ADD CONSTRAINT prescribing_checklist_items_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.prescribing_encounter_addenda
    ADD CONSTRAINT prescribing_encounter_addenda_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES __TENANT_SCHEMA__.prescribing_encounters(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.prescribing_encounter_addenda
    ADD CONSTRAINT prescribing_encounter_addenda_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.prescribing_encounters
    ADD CONSTRAINT prescribing_encounters_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.prescriptions
    ADD CONSTRAINT prescriptions_encounter_id_fkey FOREIGN KEY (encounter_id) REFERENCES __TENANT_SCHEMA__.prescribing_encounters(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.prescriptions
    ADD CONSTRAINT prescriptions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.supervision_hours
    ADD CONSTRAINT supervision_hours_supervision_relationship_id_fkey FOREIGN KEY (supervision_relationship_id) REFERENCES __TENANT_SCHEMA__.supervision_relationships(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.supervision_relationships
    ADD CONSTRAINT supervision_relationships_compliance_item_id_fkey FOREIGN KEY (compliance_item_id) REFERENCES __TENANT_SCHEMA__.compliance_items(id) ON DELETE CASCADE;



ALTER TABLE ONLY __TENANT_SCHEMA__.therapy_sessions
    ADD CONSTRAINT therapy_sessions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES __TENANT_SCHEMA__.patients(id) ON DELETE CASCADE;



CREATE POLICY rls_audit_actor_access ON __TENANT_SCHEMA__.audit_logs USING (((user_id)::text = current_setting('app.current_user_id'::text, true))) WITH CHECK (((((actor_type)::text IS DISTINCT FROM 'patient'::text) AND ((user_id)::text = current_setting('app.current_user_id'::text, true))) OR (((actor_type)::text = 'patient'::text) AND ((user_id)::text = current_setting('app.current_patient_id'::text, true)))));



CREATE POLICY rls_audit_purge_delete ON __TENANT_SCHEMA__.audit_logs FOR DELETE USING ((current_setting('app.allow_audit_purge'::text, true) = 'on'::text));



CREATE POLICY rls_audit_purge_select ON __TENANT_SCHEMA__.audit_logs FOR SELECT USING ((current_setting('app.allow_audit_purge'::text, true) = 'on'::text));



CREATE POLICY rls_patient_doc_access ON __TENANT_SCHEMA__.patient_documents USING (((((category)::text <> ALL ((ARRAY['therapist_private'::character varying, 'psychotherapy_notes'::character varying])::text[])) AND __TENANT_SCHEMA__.has_patient_access(patient_id, (current_setting('app.current_user_id'::text, true))::character varying)) OR (((category)::text = ANY ((ARRAY['therapist_private'::character varying, 'psychotherapy_notes'::character varying])::text[])) AND ((user_id)::text = current_setting('app.current_user_id'::text, true)))));
