"""Convert UUIDv4-shaped String(128) ID columns to native Postgres UUID

Every domain ID generated by the app as ``str(uuid.uuid4())`` was stored
in a ``VARCHAR(128)`` column. Native ``UUID`` is 16 bytes vs 37 bytes per
row, indexes more compactly, and rejects malformed values at the DB
level. This migration converts those columns in place; the data parses
because every existing row holds a UUID4 string.

Scope (PHI and admin tables whose ``id`` is uuid4()):

  patients.id
  therapy_sessions.id, .patient_id
  notes.id, .patient_id, .session_id
  appointments.id, .patient_id, .session_id, .recurring_appointment_id
  availability_rules.id
  compliance_items.id
  compliance_documents.id, .compliance_item_id
  chat_conversations.id, .patient_id
  chat_messages.id, .conversation_id
  audit_logs.id, .patient_id, .session_id
  patient_clinicians.patient_id
  ical_client_mappings.patient_id
  compliance_reminder_dispatches.compliance_item_id  (saas-overlay table; no-op when absent)
  platform.platform_audit_logs.id

Explicitly NOT converted:

  *.user_id (Firebase uid, not a uuid; deferred to Phase C)
  audit_logs.resource_id (polymorphic; holds user_id when the
                          resource is a user, so cannot be UUID)
  practice/tenant slugs and other opaque strings

Each ALTER is wrapped in a guard so it is a no-op when the column is
already ``uuid`` — this matters because Alembic per-tenant fan-out
replays platform-schema DDL against every tenant connection, and
because env.py's ``create_all`` on a fresh deploy will already have
materialised the platform tables with the new model types.

Foreign-key constraints touching the converted columns must be
dropped before altering and re-created afterward — Postgres rejects
an ALTER COLUMN TYPE that would leave an FK with incompatible
parent/child types, even when both sides are being altered in the
same transaction (only DEFERRABLE constraints get the deferred-check
treatment, and these are not declared DEFERRABLE). The drop/recreate
is automated via pg_constraint / pg_get_constraintdef so we don't
have to maintain a hardcoded FK list as the schema evolves.

Revision ID: b7e25c1d8a4f
Revises: a4c91b6e3f08
Create Date: 2026-05-14
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "b7e25c1d8a4f"
down_revision: str | Sequence[str] | None = "a4c91b6e3f08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# (table, column) pairs in the per-tenant practice schema
TENANT_COLUMNS: list[tuple[str, str]] = [
    ("patients", "id"),
    ("therapy_sessions", "id"),
    ("therapy_sessions", "patient_id"),
    ("notes", "id"),
    ("notes", "patient_id"),
    ("notes", "session_id"),
    ("appointments", "id"),
    ("appointments", "patient_id"),
    ("appointments", "session_id"),
    ("appointments", "recurring_appointment_id"),
    ("availability_rules", "id"),
    ("compliance_items", "id"),
    ("compliance_documents", "id"),
    ("compliance_documents", "compliance_item_id"),
    ("chat_conversations", "id"),
    ("chat_conversations", "patient_id"),
    ("chat_messages", "id"),
    ("chat_messages", "conversation_id"),
    ("audit_logs", "id"),
    ("audit_logs", "patient_id"),
    ("audit_logs", "session_id"),
    ("patient_clinicians", "patient_id"),
    ("ical_client_mappings", "patient_id"),
    # SaaS-overlay-only table (created by saas-tenant migration a4f1c8e7b2d6
    # ahead of this OSS chain on existing tenants). If present, its FK
    # column to compliance_items.id must move in lockstep so the FK can be
    # re-created at the end of this migration. ``_alter_to_uuid_in_current_schema``
    # is a no-op when the table doesn't exist (e.g. self-hosted OSS without
    # the overlay).
    ("compliance_reminder_dispatches", "compliance_item_id"),
]

# (schema, table, column) in the shared platform schema
PLATFORM_COLUMNS: list[tuple[str, str, str]] = [
    ("platform", "platform_audit_logs", "id"),
]


def _alter_to_uuid_in_current_schema(table: str, column: str) -> None:
    """ALTER TABLE <current_schema>.<table>.<column> TYPE uuid, idempotent."""
    # Identifiers are module-level constants, not user input
    sql = f"""DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = '{table}'
                  AND column_name = '{column}'
                  AND data_type = 'character varying'
            ) THEN
                EXECUTE 'ALTER TABLE {table}
                         ALTER COLUMN {column} TYPE uuid
                         USING {column}::uuid';
            END IF;
        END $$;"""  # noqa: S608
    op.execute(sql)


def _alter_to_uuid_in_schema(schema: str, table: str, column: str) -> None:
    """ALTER TABLE <schema>.<table>.<column> TYPE uuid, idempotent."""
    # Identifiers are module-level constants, not user input
    sql = f"""DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = '{schema}'
                  AND table_name = '{table}'
                  AND column_name = '{column}'
                  AND data_type = 'character varying'
            ) THEN
                EXECUTE 'ALTER TABLE {schema}.{table}
                         ALTER COLUMN {column} TYPE uuid
                         USING {column}::uuid';
            END IF;
        END $$;"""  # noqa: S608
    op.execute(sql)


def _alter_to_varchar_in_current_schema(table: str, column: str) -> None:
    """ALTER TABLE <current_schema>.<table>.<column> TYPE varchar(128), idempotent."""
    # Identifiers are module-level constants, not user input
    sql = f"""DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = '{table}'
                  AND column_name = '{column}'
                  AND data_type = 'uuid'
            ) THEN
                EXECUTE 'ALTER TABLE {table}
                         ALTER COLUMN {column} TYPE varchar(128)
                         USING {column}::text';
            END IF;
        END $$;"""  # noqa: S608
    op.execute(sql)


def _alter_to_varchar_in_schema(schema: str, table: str, column: str) -> None:
    # Identifiers are module-level constants, not user input
    sql = f"""DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = '{schema}'
                  AND table_name = '{table}'
                  AND column_name = '{column}'
                  AND data_type = 'uuid'
            ) THEN
                EXECUTE 'ALTER TABLE {schema}.{table}
                         ALTER COLUMN {column} TYPE varchar(128)
                         USING {column}::text';
            END IF;
        END $$;"""  # noqa: S608
    op.execute(sql)


def _affected_tenant_tables() -> set[str]:
    return {t for t, _ in TENANT_COLUMNS}


def _affected_platform_tables() -> set[tuple[str, str]]:
    return {(s, t) for s, t, _ in PLATFORM_COLUMNS}


def _drop_and_save_fks_tenant() -> None:
    """Drop every FK in current_schema whose source or target is an
    affected tenant table; save each constraint's definition to a temp
    table for later restoration."""
    table_list = ", ".join(f"'{t}'" for t in sorted(_affected_tenant_tables()))
    sql = f"""
    DROP TABLE IF EXISTS _b7e25c_saved_fks;
    CREATE TEMP TABLE _b7e25c_saved_fks (
        schema_name text NOT NULL,
        table_name text NOT NULL,
        constraint_name text NOT NULL,
        constraint_def text NOT NULL
    );

    INSERT INTO _b7e25c_saved_fks (schema_name, table_name, constraint_name, constraint_def)
    SELECT n.nspname, c.relname, con.conname, pg_get_constraintdef(con.oid)
    FROM pg_constraint con
    JOIN pg_class c  ON con.conrelid  = c.oid
    JOIN pg_namespace n ON c.relnamespace = n.oid
    LEFT JOIN pg_class rc ON con.confrelid = rc.oid
    WHERE con.contype = 'f'
      AND n.nspname = current_schema()
      AND (c.relname IN ({table_list}) OR rc.relname IN ({table_list}));

    DO $$
    DECLARE r RECORD;
    BEGIN
        FOR r IN SELECT * FROM _b7e25c_saved_fks LOOP
            EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT %I',
                           r.schema_name, r.table_name, r.constraint_name);
        END LOOP;
    END $$;
    """  # noqa: S608  -- identifiers are module-level constants
    op.execute(sql)


def _restore_fks_tenant() -> None:
    """Re-create every FK saved by ``_drop_and_save_fks_tenant``."""
    sql = """
    DO $$
    DECLARE r RECORD;
    BEGIN
        IF to_regclass('_b7e25c_saved_fks') IS NULL THEN
            RETURN;
        END IF;
        FOR r IN SELECT * FROM _b7e25c_saved_fks LOOP
            EXECUTE format('ALTER TABLE %I.%I ADD CONSTRAINT %I %s',
                           r.schema_name, r.table_name,
                           r.constraint_name, r.constraint_def);
        END LOOP;
    END $$;
    DROP TABLE IF EXISTS _b7e25c_saved_fks;
    """
    op.execute(sql)


def _drop_and_save_fks_platform() -> None:
    """Drop FKs in the platform schema touching affected platform tables."""
    schemas = sorted({s for s, _, _ in PLATFORM_COLUMNS})
    tables = sorted({t for _, t, _ in PLATFORM_COLUMNS})
    schema_list = ", ".join(f"'{s}'" for s in schemas)
    table_list = ", ".join(f"'{t}'" for t in tables)
    sql = f"""
    DROP TABLE IF EXISTS _b7e25c_saved_platform_fks;
    CREATE TEMP TABLE _b7e25c_saved_platform_fks (
        schema_name text NOT NULL,
        table_name text NOT NULL,
        constraint_name text NOT NULL,
        constraint_def text NOT NULL
    );

    INSERT INTO _b7e25c_saved_platform_fks
        (schema_name, table_name, constraint_name, constraint_def)
    SELECT n.nspname, c.relname, con.conname, pg_get_constraintdef(con.oid)
    FROM pg_constraint con
    JOIN pg_class c  ON con.conrelid  = c.oid
    JOIN pg_namespace n ON c.relnamespace = n.oid
    LEFT JOIN pg_class rc ON con.confrelid = rc.oid
    LEFT JOIN pg_namespace rn ON rc.relnamespace = rn.oid
    WHERE con.contype = 'f'
      AND n.nspname IN ({schema_list})
      AND (
          c.relname IN ({table_list})
          OR (rc.relname IS NOT NULL
              AND rn.nspname IN ({schema_list})
              AND rc.relname IN ({table_list}))
      );

    DO $$
    DECLARE r RECORD;
    BEGIN
        FOR r IN SELECT * FROM _b7e25c_saved_platform_fks LOOP
            EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT %I',
                           r.schema_name, r.table_name, r.constraint_name);
        END LOOP;
    END $$;
    """  # noqa: S608  -- identifiers are module-level constants
    op.execute(sql)


def _restore_fks_platform() -> None:
    sql = """
    DO $$
    DECLARE r RECORD;
    BEGIN
        IF to_regclass('_b7e25c_saved_platform_fks') IS NULL THEN
            RETURN;
        END IF;
        FOR r IN SELECT * FROM _b7e25c_saved_platform_fks LOOP
            EXECUTE format('ALTER TABLE %I.%I ADD CONSTRAINT %I %s',
                           r.schema_name, r.table_name,
                           r.constraint_name, r.constraint_def);
        END LOOP;
    END $$;
    DROP TABLE IF EXISTS _b7e25c_saved_platform_fks;
    """
    op.execute(sql)


def upgrade() -> None:
    # Per-tenant fan-out: drop FKs in this schema, alter columns, restore.
    _drop_and_save_fks_tenant()
    for table, column in TENANT_COLUMNS:
        _alter_to_uuid_in_current_schema(table, column)
    _restore_fks_tenant()

    # Platform schema (idempotent across tenant fan-out invocations).
    _drop_and_save_fks_platform()
    for schema, table, column in PLATFORM_COLUMNS:
        _alter_to_uuid_in_schema(schema, table, column)
    _restore_fks_platform()


def downgrade() -> None:
    # Mirror of upgrade(); reverse order so FK-referencing columns revert
    # before their parents within each schema.
    _drop_and_save_fks_platform()
    for schema, table, column in reversed(PLATFORM_COLUMNS):
        _alter_to_varchar_in_schema(schema, table, column)
    _restore_fks_platform()

    _drop_and_save_fks_tenant()
    for table, column in reversed(TENANT_COLUMNS):
        _alter_to_varchar_in_current_schema(table, column)
    _restore_fks_tenant()
