"""Convert UUIDv4-shaped String(128) ID columns to native Postgres UUID

Every domain ID generated by the app as ``str(uuid.uuid4())`` was stored
in a ``VARCHAR(128)`` column. Native ``UUID`` is 16 bytes vs 37 bytes per
row, indexes more compactly, and rejects malformed values at the DB
level. This migration converts those columns in place; the data parses
because every existing row holds a UUID4 string.

Scope (PHI and admin tables whose ``id`` is uuid4()):

  patients.id
  therapy_sessions.id, .patient_id
  notes.id, .patient_id, .session_id
  appointments.id, .patient_id, .session_id, .recurring_appointment_id
  availability_rules.id
  compliance_items.id
  compliance_documents.id, .compliance_item_id
  chat_conversations.id, .patient_id
  chat_messages.id, .conversation_id
  audit_logs.id, .patient_id, .session_id
  patient_clinicians.patient_id
  ical_client_mappings.patient_id
  platform.platform_audit_logs.id

Explicitly NOT converted:

  *.user_id (Firebase uid, not a uuid; deferred to Phase C)
  audit_logs.resource_id (polymorphic; holds user_id when the
                          resource is a user, so cannot be UUID)
  practice/tenant slugs and other opaque strings

Each ALTER is wrapped in a guard so it is a no-op when the column is
already ``uuid`` — this matters because Alembic per-tenant fan-out
replays platform-schema DDL against every tenant connection, and
because env.py's ``create_all`` on a fresh deploy will already have
materialised the platform tables with the new model types.

Three foreign-key constraints touch UUID-typed columns. Postgres
handles them automatically when both sides change in the same
transaction; nothing to drop/recreate.

Revision ID: b7e25c1d8a4f
Revises: a4c91b6e3f08
Create Date: 2026-05-14
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "b7e25c1d8a4f"
down_revision: str | Sequence[str] | None = "a4c91b6e3f08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# (table, column) pairs in the per-tenant practice schema
TENANT_COLUMNS: list[tuple[str, str]] = [
    ("patients", "id"),
    ("therapy_sessions", "id"),
    ("therapy_sessions", "patient_id"),
    ("notes", "id"),
    ("notes", "patient_id"),
    ("notes", "session_id"),
    ("appointments", "id"),
    ("appointments", "patient_id"),
    ("appointments", "session_id"),
    ("appointments", "recurring_appointment_id"),
    ("availability_rules", "id"),
    ("compliance_items", "id"),
    ("compliance_documents", "id"),
    ("compliance_documents", "compliance_item_id"),
    ("chat_conversations", "id"),
    ("chat_conversations", "patient_id"),
    ("chat_messages", "id"),
    ("chat_messages", "conversation_id"),
    ("audit_logs", "id"),
    ("audit_logs", "patient_id"),
    ("audit_logs", "session_id"),
    ("patient_clinicians", "patient_id"),
    ("ical_client_mappings", "patient_id"),
]

# (schema, table, column) in the shared platform schema
PLATFORM_COLUMNS: list[tuple[str, str, str]] = [
    ("platform", "platform_audit_logs", "id"),
]


def _alter_to_uuid_in_current_schema(table: str, column: str) -> None:
    """ALTER TABLE <current_schema>.<table>.<column> TYPE uuid, idempotent."""
    # Identifiers are module-level constants, not user input
    sql = f"""DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = '{table}'
                  AND column_name = '{column}'
                  AND data_type = 'character varying'
            ) THEN
                EXECUTE 'ALTER TABLE {table}
                         ALTER COLUMN {column} TYPE uuid
                         USING {column}::uuid';
            END IF;
        END $$;"""  # noqa: S608
    op.execute(sql)


def _alter_to_uuid_in_schema(schema: str, table: str, column: str) -> None:
    """ALTER TABLE <schema>.<table>.<column> TYPE uuid, idempotent."""
    # Identifiers are module-level constants, not user input
    sql = f"""DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = '{schema}'
                  AND table_name = '{table}'
                  AND column_name = '{column}'
                  AND data_type = 'character varying'
            ) THEN
                EXECUTE 'ALTER TABLE {schema}.{table}
                         ALTER COLUMN {column} TYPE uuid
                         USING {column}::uuid';
            END IF;
        END $$;"""  # noqa: S608
    op.execute(sql)


def _alter_to_varchar_in_current_schema(table: str, column: str) -> None:
    """ALTER TABLE <current_schema>.<table>.<column> TYPE varchar(128), idempotent."""
    # Identifiers are module-level constants, not user input
    sql = f"""DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = '{table}'
                  AND column_name = '{column}'
                  AND data_type = 'uuid'
            ) THEN
                EXECUTE 'ALTER TABLE {table}
                         ALTER COLUMN {column} TYPE varchar(128)
                         USING {column}::text';
            END IF;
        END $$;"""  # noqa: S608
    op.execute(sql)


def _alter_to_varchar_in_schema(schema: str, table: str, column: str) -> None:
    # Identifiers are module-level constants, not user input
    sql = f"""DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = '{schema}'
                  AND table_name = '{table}'
                  AND column_name = '{column}'
                  AND data_type = 'uuid'
            ) THEN
                EXECUTE 'ALTER TABLE {schema}.{table}
                         ALTER COLUMN {column} TYPE varchar(128)
                         USING {column}::text';
            END IF;
        END $$;"""  # noqa: S608
    op.execute(sql)


def upgrade() -> None:
    for table, column in TENANT_COLUMNS:
        _alter_to_uuid_in_current_schema(table, column)
    for schema, table, column in PLATFORM_COLUMNS:
        _alter_to_uuid_in_schema(schema, table, column)


def downgrade() -> None:
    # Reverse order so FK-referencing columns revert before their parents.
    for schema, table, column in reversed(PLATFORM_COLUMNS):
        _alter_to_varchar_in_schema(schema, table, column)
    for table, column in reversed(TENANT_COLUMNS):
        _alter_to_varchar_in_current_schema(table, column)
