"""initial practice schema

Revision ID: d20c4753ded3
Revises: 
Create Date: 2026-04-08 19:41:39.365628

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd20c4753ded3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_emails',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=False),
    sa.Column('added_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('appointments',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_at', sa.String(length=30), nullable=False),
    sa.Column('end_at', sa.String(length=30), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('session_type', sa.String(length=30), nullable=False),
    sa.Column('video_link', sa.Text(), nullable=True),
    sa.Column('video_platform', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=50), nullable=True),
    sa.Column('recurring_appointment_id', sa.String(length=128), nullable=True),
    sa.Column('recurrence_index', sa.Integer(), nullable=True),
    sa.Column('is_exception', sa.Boolean(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('google_sync_status', sa.String(length=20), nullable=True),
    sa.Column('ical_uid', sa.String(length=255), nullable=True),
    sa.Column('ical_source', sa.String(length=50), nullable=True),
    sa.Column('ical_sync_status', sa.String(length=20), nullable=True),
    sa.Column('ehr_appointment_url', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('reminder_24h_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_1h_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_ical_source'), 'appointments', ['ical_source'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_recurring_appointment_id'), 'appointments', ['recurring_appointment_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_at'), 'appointments', ['start_at'], unique=False)
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    op.create_table('availability_rules',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('enforcement', sa.String(length=10), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_rules_user_id'), 'availability_rules', ['user_id'], unique=False)
    op.create_table('ehr_prompts',
    sa.Column('ehr_system', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('ehr_system')
    )
    op.create_table('ehr_routes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('ehr_system', sa.String(length=50), nullable=False),
    sa.Column('route_name', sa.String(length=255), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('last_success', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ehr_routes_ehr_system'), 'ehr_routes', ['ehr_system'], unique=False)
    op.create_table('google_calendar_tokens',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('encrypted_tokens', sa.Text(), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=True),
    sa.Column('sync_token', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.String(length=30), nullable=True),
    sa.Column('connected_at', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ical_client_mappings',
    sa.Column('doc_id', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('ehr_system', sa.String(length=50), nullable=False),
    sa.Column('client_identifier', sa.String(length=255), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_ical_client_mappings_user_id'), 'ical_client_mappings', ['user_id'], unique=False)
    op.create_table('ical_sync_configs',
    sa.Column('doc_id', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('ehr_system', sa.String(length=50), nullable=False),
    sa.Column('encrypted_feed_url', sa.Text(), nullable=False),
    sa.Column('last_synced_at', sa.String(length=30), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_ical_sync_configs_user_id'), 'ical_sync_configs', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name_lower', sa.String(length=255), nullable=False),
    sa.Column('last_name_lower', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('last_session_date', sa.String(length=30), nullable=True),
    sa.Column('next_session_date', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_first_name_lower'), 'patients', ['first_name_lower'], unique=False)
    op.create_index(op.f('ix_patients_last_name_lower'), 'patients', ['last_name_lower'], unique=False)
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=False)
    op.create_table('therapy_sessions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('patient_id', sa.String(length=128), nullable=False),
    sa.Column('session_date', sa.String(length=30), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.String(length=30), nullable=True),
    sa.Column('video_link', sa.Text(), nullable=True),
    sa.Column('video_platform', sa.String(length=30), nullable=True),
    sa.Column('session_type', sa.String(length=30), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.String(length=30), nullable=True),
    sa.Column('ended_at', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.String(length=30), nullable=True),
    sa.Column('audio_gcs_path', sa.Text(), nullable=True),
    sa.Column('soap_note', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soap_note_edited', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('quality_rating_reason', sa.Text(), nullable=True),
    sa.Column('quality_rating_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_started_at', sa.String(length=30), nullable=True),
    sa.Column('processing_completed_at', sa.String(length=30), nullable=True),
    sa.Column('finalized_at', sa.String(length=30), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('redacted_transcript', sa.Text(), nullable=True),
    sa.Column('naturalized_transcript', sa.Text(), nullable=True),
    sa.Column('redacted_soap_note', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('naturalized_soap_note', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('export_status', sa.String(length=20), nullable=False),
    sa.Column('export_queued_at', sa.String(length=30), nullable=True),
    sa.Column('export_reviewed_at', sa.String(length=30), nullable=True),
    sa.Column('export_reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('exported_at', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_therapy_sessions_patient_id'), 'therapy_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_scheduled_at'), 'therapy_sessions', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_session_date'), 'therapy_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_therapy_sessions_user_id'), 'therapy_sessions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('credentials', sa.String(length=100), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('baa_accepted_at', sa.String(length=30), nullable=True),
    sa.Column('baa_version', sa.String(length=10), nullable=True),
    sa.Column('baa_legal_name', sa.String(length=255), nullable=True),
    sa.Column('baa_license_number', sa.String(length=100), nullable=True),
    sa.Column('baa_license_state', sa.String(length=2), nullable=True),
    sa.Column('baa_practice_name', sa.String(length=255), nullable=True),
    sa.Column('baa_business_address', sa.String(length=500), nullable=True),
    sa.Column('baa_full_text', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mfa_enrolled_at', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # Platform tables (practices, subscriptions, etc.) are managed by
    # PlatformBase.metadata.create_all() — not by Alembic migrations.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Platform tables are managed separately — not by Alembic.
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_therapy_sessions_user_id'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_session_date'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_scheduled_at'), table_name='therapy_sessions')
    op.drop_index(op.f('ix_therapy_sessions_patient_id'), table_name='therapy_sessions')
    op.drop_table('therapy_sessions')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_last_name_lower'), table_name='patients')
    op.drop_index(op.f('ix_patients_first_name_lower'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_ical_sync_configs_user_id'), table_name='ical_sync_configs')
    op.drop_table('ical_sync_configs')
    op.drop_index(op.f('ix_ical_client_mappings_user_id'), table_name='ical_client_mappings')
    op.drop_table('ical_client_mappings')
    op.drop_table('google_calendar_tokens')
    op.drop_index(op.f('ix_ehr_routes_ehr_system'), table_name='ehr_routes')
    op.drop_table('ehr_routes')
    op.drop_table('ehr_prompts')
    op.drop_index(op.f('ix_availability_rules_user_id'), table_name='availability_rules')
    op.drop_table('availability_rules')
    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_recurring_appointment_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_ical_source'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('allowed_emails')
    # ### end Alembic commands ###
