// Copyright (c) 2026 Pablo Health, LLC. Licensed under AGPL-3.0.

"use client"

import { useRef, useState } from "react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { usePatientList } from "@/hooks/usePatients"
import {
  useCreateAppointment,
  useUpdateAppointment,
  useCancelAppointment,
} from "@/hooks/useAppointments"
import type { AppointmentResponse } from "@/types/scheduling"
import type { PatientResponse } from "@/types/patients"
import type { UserPreferences } from "@/lib/api/users"

const SESSION_TYPE_LABELS: Record<string, string> = {
  individual: "Individual",
  couples: "Couples",
  group: "Group",
}

function buildTitle(patient: PatientResponse | undefined, sessionType: string): string {
  if (!patient) return ""
  const label = SESSION_TYPE_LABELS[sessionType] ?? sessionType
  return `${patient.first_name} ${patient.last_name} - ${label}`
}

interface AppointmentModalProps {
  open: boolean
  onClose: () => void
  defaultStart?: string
  defaultEnd?: string
  appointment?: AppointmentResponse | null
  preferences?: UserPreferences
}

function toLocalDatetime(iso: string): string {
  if (!iso) return ""
  const d = new Date(iso)
  const offset = d.getTimezoneOffset()
  const local = new Date(d.getTime() - offset * 60000)
  return local.toISOString().slice(0, 16)
}

function toUTC(localDatetime: string): string {
  if (!localDatetime) return ""
  return new Date(localDatetime).toISOString()
}

function formKey(
  appointment: AppointmentResponse | null | undefined,
  defaultStart?: string,
): string {
  if (appointment) return `edit-${appointment.id}-${appointment.updated_at}`
  return `new-${defaultStart ?? "empty"}`
}

export function AppointmentModal({
  open,
  onClose,
  defaultStart,
  defaultEnd,
  appointment,
  preferences,
}: AppointmentModalProps) {
  return (
    <Dialog open={open} onOpenChange={(isOpen) => !isOpen && onClose()}>
      <DialogContent className="sm:max-w-[540px] overflow-y-auto max-h-[85vh]">
        <DialogHeader>
          <DialogTitle>
            {appointment ? "Edit Appointment" : "New Appointment"}
          </DialogTitle>
          <DialogDescription>
            {appointment
              ? "Update appointment details below."
              : "Fill in the details to schedule a new appointment."}
          </DialogDescription>
        </DialogHeader>
        <AppointmentForm
          key={formKey(appointment, defaultStart)}
          appointment={appointment ?? null}
          defaultStart={defaultStart}
          defaultEnd={defaultEnd}
          onClose={onClose}
          preferences={preferences}
        />
      </DialogContent>
    </Dialog>
  )
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-xs font-medium uppercase tracking-wider text-neutral-500 pt-1">
      {children}
    </p>
  )
}

function AppointmentForm({
  appointment,
  defaultStart,
  defaultEnd,
  onClose,
  preferences,
}: {
  appointment: AppointmentResponse | null
  defaultStart?: string
  defaultEnd?: string
  onClose: () => void
  preferences?: UserPreferences
}) {
  const { data: patientData } = usePatientList()
  const patients = patientData?.data ?? []

  const createMutation = useCreateAppointment()
  const updateMutation = useUpdateAppointment()
  const cancelMutation = useCancelAppointment()

  const isEditing = !!appointment
  const titleAutoGenerated = useRef(!isEditing)

  const defaultDuration = appointment?.duration_minutes ?? preferences?.default_duration_minutes ?? 50
  const defaultSessionType = appointment?.session_type ?? preferences?.default_session_type ?? "individual"
  const defaultVideoPlatform = appointment?.video_platform ?? preferences?.default_video_platform ?? ""

  const [patientId, setPatientId] = useState(appointment?.patient_id ?? "")
  const [title, setTitle] = useState(appointment?.title ?? "")
  const [startAt, setStartAt] = useState(
    appointment ? toLocalDatetime(appointment.start_at) : defaultStart ? toLocalDatetime(defaultStart) : ""
  )
  const [endAt, setEndAt] = useState(() => {
    if (appointment) return toLocalDatetime(appointment.end_at)
    if (defaultEnd) return toLocalDatetime(defaultEnd)
    if (defaultStart) {
      const end = new Date(new Date(defaultStart).getTime() + defaultDuration * 60000)
      return toLocalDatetime(end.toISOString())
    }
    return ""
  })
  const [durationMinutes, setDurationMinutes] = useState(defaultDuration)
  const [sessionType, setSessionType] = useState(defaultSessionType)
  const [videoLink, setVideoLink] = useState(appointment?.video_link ?? "")
  const [videoPlatform] = useState(defaultVideoPlatform)
  const [notes, setNotes] = useState(appointment?.notes ?? "")

  const handlePatientChange = (id: string) => {
    setPatientId(id)
    if (titleAutoGenerated.current) {
      const patient = patients.find((p) => p.id === id)
      setTitle(buildTitle(patient, sessionType))
    }
  }

  const handleSessionTypeChange = (type: string) => {
    setSessionType(type)
    if (titleAutoGenerated.current && patientId) {
      const patient = patients.find((p) => p.id === patientId)
      setTitle(buildTitle(patient, type))
    }
  }

  const handleTitleChange = (value: string) => {
    setTitle(value)
    titleAutoGenerated.current = false
  }

  const handleStartChange = (value: string) => {
    setStartAt(value)
    if (value && durationMinutes > 0) {
      const start = new Date(value)
      const end = new Date(start.getTime() + durationMinutes * 60000)
      const offset = end.getTimezoneOffset()
      const localEnd = new Date(end.getTime() - offset * 60000)
      setEndAt(localEnd.toISOString().slice(0, 16))
    }
  }

  const handleSubmit = () => {
    if (isEditing && appointment) {
      updateMutation.mutate(
        {
          appointmentId: appointment.id,
          data: {
            title,
            patient_id: patientId,
            start_at: toUTC(startAt),
            end_at: toUTC(endAt),
            duration_minutes: durationMinutes,
            session_type: sessionType,
            video_link: videoLink || null,
            video_platform: videoPlatform || null,
            notes: notes || null,
          },
        },
        { onSuccess: onClose }
      )
    } else {
      createMutation.mutate(
        {
          patient_id: patientId,
          title,
          start_at: toUTC(startAt),
          end_at: toUTC(endAt),
          duration_minutes: durationMinutes,
          session_type: sessionType,
          video_link: videoLink || null,
          video_platform: videoPlatform || null,
          notes: notes || null,
        },
        { onSuccess: onClose }
      )
    }
  }

  const handleCancel = () => {
    if (appointment) {
      cancelMutation.mutate(appointment.id, { onSuccess: onClose })
    }
  }

  const isSubmitting = createMutation.isPending || updateMutation.isPending

  return (
    <>
      <div className="grid gap-5 py-4">
        {/* Patient & Title */}
        <SectionLabel>Patient &amp; Title</SectionLabel>
        <div className="grid gap-2">
          <Label htmlFor="patient">Patient</Label>
          <Select value={patientId} onValueChange={handlePatientChange}>
            <SelectTrigger id="patient" aria-required="true">
              <SelectValue placeholder="Select patient" />
            </SelectTrigger>
            <SelectContent>
              {patients.map((p) => (
                <SelectItem key={p.id} value={p.id}>
                  {p.last_name}, {p.first_name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="grid gap-2">
          <Label htmlFor="title">Title</Label>
          <Input
            id="title"
            value={title}
            onChange={(e) => handleTitleChange(e.target.value)}
            placeholder="Session with patient"
          />
        </div>

        {/* Schedule */}
        <div className="border-t border-neutral-100" />
        <SectionLabel>Schedule</SectionLabel>
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-2">
            <Label htmlFor="start">Start</Label>
            <Input
              id="start"
              type="datetime-local"
              value={startAt}
              onChange={(e) => handleStartChange(e.target.value)}
              aria-required="true"
            />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="duration">Duration (min)</Label>
            <Input
              id="duration"
              type="number"
              min={1}
              max={480}
              value={durationMinutes}
              onChange={(e) => setDurationMinutes(Number(e.target.value))}
            />
          </div>
        </div>

        {/* Session Details */}
        <div className="border-t border-neutral-100" />
        <SectionLabel>Session Details</SectionLabel>
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-2">
            <Label htmlFor="session-type">Session Type</Label>
            <Select value={sessionType} onValueChange={handleSessionTypeChange}>
              <SelectTrigger id="session-type">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="individual">Individual</SelectItem>
                <SelectItem value="couples">Couples</SelectItem>
                <SelectItem value="group">Group</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="video-link">Video Link</Label>
            <Input
              id="video-link"
              value={videoLink}
              onChange={(e) => setVideoLink(e.target.value)}
              placeholder="https://zoom.us/j/..."
            />
          </div>
        </div>

        {/* Notes */}
        <div className="border-t border-neutral-100" />
        <SectionLabel>Notes</SectionLabel>
        <div className="grid gap-2">
          <Label htmlFor="notes">Notes</Label>
          <Textarea
            id="notes"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            rows={3}
          />
        </div>
      </div>

      <DialogFooter className="flex justify-between">
        {isEditing && appointment?.status !== "cancelled" && (
          <Button
            variant="destructive"
            onClick={handleCancel}
            disabled={cancelMutation.isPending}
          >
            Cancel Appointment
          </Button>
        )}
        <div className="flex gap-2 ml-auto">
          <Button variant="outline" onClick={onClose}>
            Close
          </Button>
          <Button onClick={handleSubmit} disabled={!patientId || !title || !startAt || !endAt || isSubmitting}>
            {isEditing ? "Save Changes" : "Create"}
          </Button>
        </div>
      </DialogFooter>
    </>
  )
}
